chigraph: chi::Debugger Class Reference
chi::Debugger Class Reference
Helper class for using LLDB with chigraph.
#include <chi/Debugger.hpp>
Public Member Functions
Debugger (const char *pathToChig, GraphModule &mod)
Default constructor.
Debugger (const Debugger &other)=delete
Debugger (Debugger &&other)=delete
~Debugger ()
Destructor.
lldb::SBValue inspectLocalVariable (boost::string_view name)
Get the value of a local variable.
lldb::SBValue inspectNodeOutput (const NodeInstance &inst, size_t id, lldb::SBFrame frame={})
Get the output of a node.
bool isAttached () const
Check if this debugger is attached to a process It's true if the process is stopped or if it's curretnly executing.
std::vector< const NodeInstance * > listBreakpoints () const
List the curretnly set breakpoints.
lldb::SBDebugger lldbDebugger () const
Get the debugger This should probably be valid...not sure why it wouldn't be.
lldb::SBProcess lldbProcess () const
Get the process This will only be valid if there's an attached process.
lldb::SBTarget lldbTarget () const
Get the target Keep in mind the return isn't necessarily valid, although it should be.
GraphModule & module () const
Get the module that's being debugged by this debugger.
NodeInstance * nodeFromFrame (lldb::SBFrame frame={})
Get a NodeInstance from a frame.
Debugger & operator= (const Debugger &)=delete
Debugger & operator= (Debugger &&)=delete
Result pause ()
Pause the execution state.
Result processContinue ()
Continue the execution of the process.
bool removeBreakpoint (NodeInstance &node)
Remove a breakpoint from a node.
bool running () const
Check if the process is executing.
Result setBreakpoint (NodeInstance &node, lldb::SBBreakpoint *bp=nullptr)
Set a breakpoint on a given node.
Result start (const char **argv=nullptr, const char **envp=nullptr, const boost::filesystem::path &workingDirectory=boost::filesystem::current_path())
Start debugging the process.
Result terminate ()
Terminate the inferior process.
Detailed Description
Helper class for using LLDB with chigraph.
Definition at line 20 of file Debugger.hpp.
Constructor & Destructor Documentation
Debugger()
chi::Debugger::Debugger (const char * pathToChig, GraphModule & mod)
Default constructor.
Parameters
pathToChig The path to the chig executable for JIT
mod The GraphModule to debug, should be a main module
Definition at line 27 of file Debugger.cpp.
Member Function Documentation
inspectLocalVariable()
lldb::SBValue chi::Debugger::inspectLocalVariable (boost::string_view name)
Get the value of a local variable.
Parameters
name The name ofthe local variable to get the value of
Returns
The value, or an invalid SBValue if the local variable wasn't found
Referenced by running().
inspectNodeOutput()
lldb::SBValue chi::Debugger::inspectNodeOutput (const NodeInstance & inst, size_t id, lldb::SBFrame frame = {})
Get the output of a node.
Parameters
inst The instance
id The ID of output to get
Precondition
id < inst.outputDataConnections.size()
Parameters
frame The frame. If this isn't a valid SBFrame (the default), then it uses lldbProcess().GetSelectedThread().GetSelectedFrame()
Definition at line 199 of file Debugger.cpp.
References chi::NodeInstance::function(), lldbProcess(), nodeFromFrame(), chi::NodeInstance::outputDataConnections, and chi::NodeInstance::stringId().
Referenced by running().
isAttached()
bool chi::Debugger::isAttached () const inline
Check if this debugger is attached to a process It's true if the process is stopped or if it's curretnly executing.
Returns
True if it's attached
Definition at line 57 of file Debugger.hpp.
Referenced by pause(), processContinue(), running(), and terminate().
listBreakpoints()
std::vector< const NodeInstance * > chi::Debugger::listBreakpoints () const
List the curretnly set breakpoints.
Returns
The breakpoints
Definition at line 192 of file Debugger.cpp.
Referenced by running().
module()
GraphModule& chi::Debugger::module () const inline
Get the module that's being debugged by this debugger.
Returns
The module
Definition at line 110 of file Debugger.hpp.
Referenced by nodeFromFrame(), and start().
nodeFromFrame()
NodeInstance * chi::Debugger::nodeFromFrame (lldb::SBFrame frame = {})
Get a NodeInstance from a frame.
Parameters
frame The frame to get the function for. If this isn't a valid SBFrame (the default), then it uses lldbProcess().GetSelectedThread().GetSelectedFrame()
Returns
The NodeInstance, or nullptr if one wasn't found
Definition at line 220 of file Debugger.cpp.
References chi::ChiModule::context(), chi::GraphModule::createLineNumberAssoc(), chi::GraphModule::functionFromName(), lldbProcess(), chi::NodeInstance::module(), module(), chi::GraphFunction::module(), chi::Context::moduleByFullName(), and chi::unmangleFunctionName().
Referenced by inspectNodeOutput(), and running().
pause()
Result chi::Debugger::pause ()
Pause the execution state.
Returns
The Result
Definition at line 81 of file Debugger.cpp.
References chi::Result::addEntry(), and isAttached().
Referenced by running().
processContinue()
Result chi::Debugger::processContinue ()
Continue the execution of the process.
Returns
The Result
Definition at line 65 of file Debugger.cpp.
References chi::Result::addEntry(), and isAttached().
Referenced by running().
removeBreakpoint()
bool chi::Debugger::removeBreakpoint (NodeInstance & node)
Remove a breakpoint from a node.
Parameters
[in] node The node to remove the breakpoint from
Returns
True if a breakpoint was removed, false otherwise
Definition at line 126 of file Debugger.cpp.
Referenced by running().
running()
bool chi::Debugger::running () const inline
Check if the process is executing.
Returns
If it's running
Definition at line 61 of file Debugger.hpp.
References inspectLocalVariable(), inspectNodeOutput(), isAttached(), listBreakpoints(), lldbProcess(), nodeFromFrame(), pause(), processContinue(), removeBreakpoint(), and setBreakpoint().
setBreakpoint()
Result chi::Debugger::setBreakpoint (NodeInstance & node, lldb::SBBreakpoint * bp = nullptr)
Set a breakpoint on a given node.
Parameters
[in] node The node to set the breakpoint on
[out] bp The (optional) SBBreakpoint object to fill
Returns
The result
Definition at line 98 of file Debugger.cpp.
References chi::Result::addEntry(), chi::NodeInstance::module(), chi::GraphModule::sourceFilePath(), and chi::NodeInstance::stringId().
Referenced by running().
start()
Result chi::Debugger::start (const char ** argv = nullptr, const char ** envp = nullptr, const boost::filesystem::path & workingDirectory = boost::filesystem::current_path())
Start debugging the process.
Parameters
[in] argv A null-terminated array of arguments. If it isn't null-terminated then this will probably crash
[in] envp A null-terminated array of environment variables. If it isn't null-terminated then this will probably crash
[in] workingDirectory The working directory to debug in, by default it's the current working directory of this process
Precondition
boost::filesystem::is_directory(workingDirectory)
Returns
The result
Definition at line 133 of file Debugger.cpp.
References chi::Result::addEntry(), chi::Context::compileModule(), chi::ChiModule::context(), and module().
terminate()
Result chi::Debugger::terminate ()
Terminate the inferior process.
Returns
The result
Definition at line 48 of file Debugger.cpp.
References chi::Result::addEntry(), and isAttached().
The documentation for this class was generated from the following files:
libchigraphdebugger/include/chi/Debugger.hpp
libchigraphdebugger/src/Debugger.cpp