chigraph: chig Namespace Reference
chig Namespace Reference
The namespace where chigraph lives.
Classes
struct ChigModule
An abstract class that represents a module of code in Chigraph Can be compiled to a llvm::Module.
struct CModule
The CModule is the module that supplies functionality to create C bindings.
struct Context
The class that handles the loading, creation, storing, and compilation of modules It also stores a LLVMContext object to be used everywhere.
struct DataType
A type of data Loose wrapper around llvm::Type*, except it knows which ChigModule its in.
struct GraphFunction
this is an AST-like representation of a function in a graph It is used for IDE-like behavior, codegen, and JSON generation.
struct GraphModule
Module that holds graph functions.
struct GraphStruct
A class holding a compound type defined in a GraphModule.
struct LangModule
The module that provides built-in operations like literals, math operations, etc.
struct NamedDataType
struct NodeInstance
An instance of a node.
struct NodeType
A generic node type.
struct Result
The result object, used for identifiying errors with good diagnostics.
Functions
Result compileFunction (const GraphFunction &func, llvm::Module *mod, llvm::DICompileUnit *debugCU, llvm::DIBuilder &debugBuilder)
Compile the graph to an llvm::Function (usually called from JsonModule::generateModule)
std::pair< std::string, std::string > parseColonPair (const std::string &in)
Parse a colonated pair Example: lang:i32 would turn into {lang, i32}.
std::string stringifyLLVMType (llvm::Type *ty)
Turns a type into a string.
boost::filesystem::path workspaceFromChildPath (const boost::filesystem::path &path)
Get the workspace directory from a child of the workspace directory Example: say you have a workspace at ~/chig/ If you used this with ~/chig/src/ it would return ~/chig/.
Function Validation
Functions for making sure that generated functions are valid (also usable as a linter tools)
Result validateFunction (const GraphFunction &func)
Validate that a function is compilable.
Result validateFunctionConnectionsAreTwoWay (const GraphFunction &func)
Make sure that connections connect back and that they have the same types.
Result validateFunctionNodeInputs (const GraphFunction &func)
The make sure that nodes are called before their outputs are used.
Json Serialization/Deserialization
Result jsonToGraphModule (Context &createInside, const nlohmann::json &input, gsl::cstring_span<> fullName, GraphModule **toFill=nullptr)
Load a GraphModule from json.
Result createGraphFunctionDeclarationFromJson (GraphModule &createInside, const nlohmann::json &input, GraphFunction **toFill=nullptr)
Create a forward declaration of a function in a module with an empty graph.
Result jsonToGraphFunction (GraphFunction &createInside, const nlohmann::json &input)
Load a GraphFunction–must already exist (use createGraphFunctionDeclarationFromJson)
Result jsonToGraphStruct (GraphModule &mod, gsl::cstring_span<> name, const nlohmann::json &input, GraphStruct **toFill=nullptr)
Load a GraphStruct from json.
std::pair< std::string, std::string > parseObjectPair (const nlohmann::json &object)
Parse something that looks like: {"hello": "there"} into {"hello", "there"}.
nlohmann::json graphFunctionToJson (const GraphFunction &func)
Serialize a GraphFunction to json.
nlohmann::json graphModuleToJson (const GraphModule &mod)
Serialize a JsonModule to json.
nlohmann::json graphStructToJson (const GraphStruct &struc)
Serialize a GraphStruct to json.
Name Mangling
Functions for mangling names into names used natively
std::string mangleFunctionName (gsl::cstring_span<> fullModuleName, gsl::cstring_span<> name)
Mangle a function name.
std::pair< std::string, std::string > unmangleFunctionName (gsl::cstring_span<> mangledName)
Unmangle a function name.
Connection Manipulation
Functions for connecting and disconnecting nodes
Result connectData (NodeInstance &lhs, size_t lhsConnID, NodeInstance &rhs, size_t rhsConnID)
Connects two nodes' data connections.
Result connectExec (NodeInstance &lhs, size_t lhsConnID, NodeInstance &rhs, size_t rhsConnID)
Connects two nodes' exec connections.
Result disconnectData (NodeInstance &lhs, size_t lhsConnID, NodeInstance &rhs)
Disconnect a data connection.
Result disconnectExec (NodeInstance &lhs, size_t lhsConnID)
Disconnect a exec connection.
Result operators
Result operator+ (const Result &lhs, const Result &rhs)
Append two Result objects.
Result & operator+= (Result &lhs, const Result &rhs)
Append one result to an existing one.
std::ostream & operator<< (std::ostream &lhs, const Result &rhs)
Stream operator.
Detailed Description
The namespace where chigraph lives.
Function Documentation
compileFunction()
Result chig::compileFunction (const GraphFunction & func, llvm::Module * mod, llvm::DICompileUnit * debugCU, llvm::DIBuilder & debugBuilder)
Compile the graph to an llvm::Function (usually called from JsonModule::generateModule)
Parameters
func The function to compile
mod The module to codgen into, should already be a valid module
debugCU The compilation unit that the GraphFunction resides in.
debugBuilder The debug builder to build debug info
Returns
The result
Definition at line 264 of file FunctionCompiler.cpp.
References chig::Result::addEntry(), chig::GraphFunction::context(), chig::GraphModule::createLineNumberAssoc(), chig::GraphFunction::dataInputs(), chig::GraphFunction::dataOutputs(), chig::DataType::debugType(), chig::GraphFunction::entryNode(), chig::ChigModule::fullName(), chig::GraphFunction::functionType(), mangleFunctionName(), chig::GraphFunction::module(), chig::GraphFunction::name(), chig::Context::typeFromModule(), chig::DataType::valid(), and validateFunction().
Referenced by chig::GraphModule::generateModule().
connectData()
Result chig::connectData (NodeInstance & lhs, size_t lhsConnID, NodeInstance & rhs, size_t rhsConnID)
Connects two nodes' data connections.
Parameters
lhs The node to the left, the node outputting the data
lhsConnID The ID of data connection in lhs to be connected
rhs The node to the right, that takes in the data as a parameter
rhsConnID The ID of data input in rhs
Returns
The result
Definition at line 106 of file NodeInstance.cpp.
References chig::Result::addEntry(), chig::NodeType::dataInputs(), chig::NodeType::dataOutputs(), disconnectData(), chig::NodeInstance::function(), chig::NodeInstance::inputDataConnections, chig::NodeInstance::outputDataConnections, chig::NodeType::qualifiedName(), chig::NodeType::toJSON(), and chig::NodeInstance::type().
Referenced by chig::NodeInstance::function(), and jsonToGraphFunction().
connectExec()
Result chig::connectExec (NodeInstance & lhs, size_t lhsConnID, NodeInstance & rhs, size_t rhsConnID)
Connects two nodes' exec connections.
Parameters
lhs The node to the left, the node outputting the connections
lhsConnID The ID of exec connection in lhs to be connected
rhs The node to the right, that takes in the exec as a parameter
rhsConnID The ID of exec input in rhs
Returns
The result
Definition at line 166 of file NodeInstance.cpp.
References chig::Result::addEntry(), disconnectExec(), chig::NodeType::execInputs(), chig::NodeType::execOutputs(), chig::NodeInstance::function(), chig::NodeInstance::inputExecConnections, chig::NodeInstance::outputExecConnections, chig::NodeType::qualifiedName(), and chig::NodeInstance::type().
Referenced by chig::NodeInstance::function(), and jsonToGraphFunction().
createGraphFunctionDeclarationFromJson()
Result chig::createGraphFunctionDeclarationFromJson (GraphModule & createInside, const nlohmann::json & input, GraphFunction ** toFill = nullptr)
Create a forward declaration of a function in a module with an empty graph.
Parameters
createInside the GraphModule to create the forward declaration in
input The input JSON The GraphFunction* to fill, optional
Definition at line 98 of file JsonDeserializer.cpp.
References chig::Result::addEntry(), chig::ChigModule::context(), chig::GraphModule::getOrCreateFunction(), parseColonPair(), parseObjectPair(), and chig::Context::typeFromModule().
Referenced by jsonToGraphModule().
disconnectData()
Result chig::disconnectData (NodeInstance & lhs, size_t lhsConnID, NodeInstance & rhs)
Disconnect a data connection.
Parameters
lhs The left hand node
lhsConnID The ID of the data connection to disconnect
rhs The node that the data port is connected to
Returns
The result
Definition at line 211 of file NodeInstance.cpp.
References chig::Result::addEntry(), chig::NodeType::dataInputs(), chig::NodeType::dataOutputs(), chig::NodeInstance::function(), chig::NodeInstance::id(), chig::NodeInstance::inputDataConnections, chig::NodeInstance::outputDataConnections, chig::NodeType::qualifiedName(), chig::NodeType::toJSON(), and chig::NodeInstance::type().
Referenced by connectData(), chig::NodeInstance::function(), chig::GraphFunction::removeNode(), and chig::NodeInstance::setType().
disconnectExec()
Result chig::disconnectExec (NodeInstance & lhs, size_t lhsConnID)
Disconnect a exec connection.
Parameters
lhs The left hand node in the connection
lhsConnID The ID of the connection on lhs
Returns
The result
Definition at line 277 of file NodeInstance.cpp.
References chig::Result::addEntry(), chig::NodeType::execOutputs(), chig::NodeInstance::id(), chig::NodeInstance::outputExecConnections, chig::NodeType::qualifiedName(), and chig::NodeInstance::type().
Referenced by connectExec(), chig::NodeInstance::function(), chig::GraphFunction::removeNode(), and chig::NodeInstance::setType().
graphFunctionToJson()
nlohmann::json chig::graphFunctionToJson (const GraphFunction & func)
Serialize a GraphFunction to json.
Parameters
func The function to serialize
Returns
The serialized function
Definition at line 10 of file JsonSerializer.cpp.
References chig::GraphFunction::dataInputs(), chig::GraphFunction::dataOutputs(), chig::GraphFunction::execInputs(), chig::GraphFunction::execOutputs(), chig::GraphFunction::localVariables(), chig::GraphFunction::name(), and chig::GraphFunction::nodes().
Referenced by graphModuleToJson().
graphModuleToJson()
nlohmann::json chig::graphModuleToJson (const GraphModule & mod)
Serialize a JsonModule to json.
Parameters
mod The module to serialize
Returns
The serialized module
Definition at line 89 of file JsonSerializer.cpp.
References chig::ChigModule::dependencies(), chig::GraphModule::functions(), graphFunctionToJson(), graphStructToJson(), and chig::ChigModule::shortName().
Referenced by chig::GraphModule::saveToDisk().
graphStructToJson()
nlohmann::json chig::graphStructToJson (const GraphStruct & struc)
Serialize a GraphStruct to json.
Parameters
struc The struct to serialize
Definition at line 106 of file JsonSerializer.cpp.
References chig::GraphStruct::types().
Referenced by graphModuleToJson().
jsonToGraphFunction()
Result chig::jsonToGraphFunction (GraphFunction & createInside, const nlohmann::json & input)
Load a GraphFunction–must already exist (use createGraphFunctionDeclarationFromJson)
Parameters
createInside The GraphFunction to create the graph for The JSON to load
Definition at line 197 of file JsonDeserializer.cpp.
References chig::Result::addEntry(), connectData(), connectExec(), chig::GraphFunction::context(), chig::GraphFunction::getOrCreateLocalVariable(), chig::GraphFunction::insertNode(), chig::GraphFunction::nodes(), chig::Context::nodeTypeFromModule(), parseColonPair(), and chig::Context::typeFromModule().
Referenced by jsonToGraphModule().
jsonToGraphModule()
Result chig::jsonToGraphModule (Context & createInside, const nlohmann::json & input, gsl::cstring_span<> fullName, GraphModule ** toFill = nullptr)
Load a GraphModule from json.
Parameters
createInside The Context to create the module in The JSON to load The GraphModule* to set, optional
Definition at line 12 of file JsonDeserializer.cpp.
References chig::Result::addEntry(), createGraphFunctionDeclarationFromJson(), jsonToGraphFunction(), jsonToGraphStruct(), and chig::Context::newGraphModule().
Referenced by chig::Context::addModuleFromJson().
jsonToGraphStruct()
Result chig::jsonToGraphStruct (GraphModule & mod, gsl::cstring_span<> name, const nlohmann::json & input, GraphStruct ** toFill = nullptr)
Load a GraphStruct from json.
Parameters
mod The module to create it inside
input The JSON to load
toFill The object to fill, optional
Definition at line 373 of file JsonDeserializer.cpp.
References chig::Result::addEntry(), chig::ChigModule::context(), chig::GraphModule::getOrCreateStruct(), parseColonPair(), parseObjectPair(), and chig::Context::typeFromModule().
Referenced by jsonToGraphModule().
mangleFunctionName()
std::string chig::mangleFunctionName (gsl::cstring_span<> fullModuleName, gsl::cstring_span<> name)
Mangle a function name.
Parameters
fullModuleName The full name of the module. Example github.com/russelltg/test/lib
name The name of the function
Returns
The mangled name
Definition at line 8 of file NameMangler.cpp.
Referenced by compileFunction(), and chig::GraphModule::generateModule().
operator+()
Result chig::operator+ (const Result & lhs, const Result & rhs) inline
Append two Result objects.
Parameters
lhs The left error
rhs The right error
Returns
The concatinated errors
Definition at line 55 of file Result.hpp.
References chig::Result::result_json, and chig::Result::success.
operator+=()
Result& chig::operator+= (Result & lhs, const Result & rhs) inline
Append one result to an existing one.
Parameters
lhs The existing Result to add to
rhs The (usually temporary) result to be added into lhs
Returns
*this
Definition at line 70 of file Result.hpp.
References chig::Result::result_json, and chig::Result::success.
operator<<()
std::ostream& chig::operator<< (std::ostream & lhs, const Result & rhs) inline
Stream operator.
Parameters
lhs The stream
rhs The Result to print to lhs
Returns
lhs after printing
Definition at line 83 of file Result.hpp.
References chig::Result::dump().
parseColonPair()
std::pair<std::string, std::string> chig::parseColonPair (const std::string & in) inline
Parse a colonated pair Example: lang:i32 would turn into {lang, i32}.
Parameters
in The colonated pair
Returns
{first, second}
Definition at line 322 of file GraphFunction.hpp.
References chig::GraphFunction::module(), and chig::GraphFunction::name().
Referenced by createGraphFunctionDeclarationFromJson(), jsonToGraphFunction(), jsonToGraphStruct(), chig::CModule::nodeTypeFromName(), and chig::GraphModule::nodeTypeFromName().
parseObjectPair()
std::pair< std::string, std::string > chig::parseObjectPair (const nlohmann::json & object)
Parse something that looks like: {"hello": "there"} into {"hello", "there"}.
Parameters
object The json object
Returns
{"key", "value"}
Definition at line 414 of file JsonDeserializer.cpp.
Referenced by createGraphFunctionDeclarationFromJson(), jsonToGraphStruct(), and chig::CModule::nodeTypeFromName().
stringifyLLVMType()
std::string chig::stringifyLLVMType (llvm::Type * ty)
Turns a type into a string.
Parameters
ty The type to stringify
Returns
The return string
Definition at line 310 of file Context.cpp.
Referenced by chig::Context::cModule(), and chig::CModule::nodeTypeFromName().
unmangleFunctionName()
std::pair< std::string, std::string > chig::unmangleFunctionName (gsl::cstring_span<> mangledName)
Unmangle a function name.
Parameters
mangledName The mangled name
Returns
The unmangled name
Definition at line 46 of file NameMangler.cpp.
validateFunction()
Result chig::validateFunction (const GraphFunction & func)
Validate that a function is compilable.
If this succeeds, then it should be compilable Calls validateFunctionConnectionsAreTwoWay and validateFunctionNodeInputs
Parameters
func The function to check
Returns
The Result
Definition at line 11 of file FunctionValidator.cpp.
References validateFunctionConnectionsAreTwoWay(), and validateFunctionNodeInputs().
Referenced by compileFunction().
validateFunctionConnectionsAreTwoWay()
Result chig::validateFunctionConnectionsAreTwoWay (const GraphFunction & func)
Make sure that connections connect back and that they have the same types.
Parameters
func The function to check
Returns
The Result
Definition at line 19 of file FunctionValidator.cpp.
References chig::Result::addEntry(), chig::NodeInstance::id(), chig::NodeInstance::inputDataConnections, chig::GraphFunction::nodes(), and chig::NodeInstance::outputExecConnections.
Referenced by validateFunction().
validateFunctionNodeInputs()
Result chig::validateFunctionNodeInputs (const GraphFunction & func)
The make sure that nodes are called before their outputs are used.
Parameters
func The function to check
Returns
The Result
Definition at line 168 of file FunctionValidator.cpp.
References chig::GraphFunction::entryNode().
Referenced by validateFunction().
workspaceFromChildPath()
boost::filesystem::path chig::workspaceFromChildPath (const boost::filesystem::path & path)
Get the workspace directory from a child of the workspace directory Example: say you have a workspace at ~/chig/ If you used this with ~/chig/src/ it would return ~/chig/.
Parameters
path The child path
Returns
The workspace path, or an empty path if it wasn't found
Definition at line 298 of file Context.cpp.
Referenced by chig::Context::cModule(), and chig::Context::Context().