chigraph: chi Namespace Reference
chi Namespace Reference
The namespace where chigraph lives.
Classes
struct ChiModule
An abstract class that represents a module of code in Chigraph Can be compiled to a llvm::Module.
struct CModule
The CModule is the module that supplies functionality to create C bindings.
struct Context
The class that handles the loading, creation, storing, and compilation of modules It also stores a LLVMContext object to be used everywhere.
struct DataType
A type of data Loose wrapper around llvm::Type*, except it knows which ChiModule it's in and it embeds debug types.
class Debugger
Helper class for using LLDB with chigraph.
struct Flags
A template class for type-safe flags.
struct GraphFunction
this is an AST-like representation of a function in a graph It is used for IDE-like behavior, codegen, and JSON generation.
struct GraphModule
Module that holds graph functions.
struct GraphStruct
A class holding a compound type defined in a GraphModule.
struct LangModule
The module that provides built-in operations like literals, math operations, etc.
struct NamedDataType
Basicaly a std::pair<std::string, DataType>, except it has nicer names.
struct NodeInstance
An instance of a node.
struct NodeType
A generic node type.
struct Result
The result object, used for identifiying errors with good diagnostics.
Enumerations
enum LoadSettings {
Default = 0u,
Fetch = 1u,
FetchRecursive = Fetch | 1u << 1
}
Settings for loading modules.
enum VCSType {
VCSType::Git,
Unknown
}
The Version Control Types.
Functions
Result compileFunction (const GraphFunction &func, llvm::Module *mod, llvm::DICompileUnit *debugCU, llvm::DIBuilder &debugBuilder)
Compile the graph to an llvm::Function (usually called from JsonModule::generateModule)
Result interpretLLVMIR (std::unique_ptr< llvm::Module > mod, llvm::CodeGenOpt::Level optLevel=llvm::CodeGenOpt::Default, std::vector< llvm::GenericValue > args={}, llvm::Function *funcToRun=nullptr, llvm::GenericValue *ret=nullptr)
Interpret LLVM IR, just a convenience function.
Result interpretLLVMIRAsMain (std::unique_ptr< llvm::Module > mod, llvm::CodeGenOpt::Level optLevel=llvm::CodeGenOpt::Default, std::vector< std::string > args={}, llvm::Function *funcToRun=nullptr, int *ret=nullptr)
Interpret LLVM IR as if it were the main function.
unsigned lineNumberFromNode (NodeInstance &inst)
std::pair< std::string, std::string > parseColonPair (const std::string &in)
Parse a colonated pair Example: lang:i32 would turn into {lang, i32}.
std::tuple< VCSType, std::string, std::string > resolveUrlFromModuleName (const boost::filesystem::path &path)
Get the URL for a VCS repository from a module name.
std::tuple< VCSType, std::string, std::string > resolveUrlFromModuleName (const fs::path &path)
std::string stringifyLLVMType (llvm::Type *ty)
Turns a type into a string.
boost::filesystem::path workspaceFromChildPath (const boost::filesystem::path &path)
Get the workspace directory from a child of the workspace directory Example: say you have a workspace at ~/chi/ If you used this with ~/chi/src/ it would return ~/chi/.
fs::path workspaceFromChildPath (const fs::path &path)
Function Validation
Functions for making sure that generated functions are valid (also usable as a linter tools)
Result validateFunction (const GraphFunction &func)
Validate that a function is compilable.
Result validateFunctionConnectionsAreTwoWay (const GraphFunction &func)
Make sure that connections connect back and that they have the same types.
Result validateFunctionNodeInputs (const GraphFunction &func)
Make sure that nodes are called before their outputs are used.
Result validateFunctionExecOutputs (const GraphFunction &func)
Make sure nodes have an output connection.
Json Serialization/Deserialization
Result jsonToGraphModule (Context &createInside, const nlohmann::json &input, const boost::filesystem::path &fullName, GraphModule **toFill=nullptr)
Load a GraphModule from json.
Result createGraphFunctionDeclarationFromJson (GraphModule &createInside, const nlohmann::json &input, GraphFunction **toFill=nullptr)
Create a forward declaration of a function in a module with an empty graph.
Result jsonToGraphFunction (GraphFunction &createInside, const nlohmann::json &input)
Load a GraphFunction–must already exist (use createGraphFunctionDeclarationFromJson)
Result jsonToGraphStruct (GraphModule &mod, boost::string_view name, const nlohmann::json &input, GraphStruct **toFill=nullptr)
Load a GraphStruct from json.
std::pair< std::string, std::string > parseObjectPair (const nlohmann::json &object)
Parse something that looks like: {"hello": "there"} into {"hello", "there"}.
nlohmann::json graphFunctionToJson (const GraphFunction &func)
Serialize a GraphFunction to json.
nlohmann::json graphModuleToJson (const GraphModule &mod)
Serialize a JsonModule to json.
nlohmann::json graphStructToJson (const GraphStruct &struc)
Serialize a GraphStruct to json.
Name Mangling
Functions for mangling names into names used natively
std::string mangleFunctionName (std::string fullModuleName, const std::string &name)
Mangle a function name.
std::pair< std::string, std::string > unmangleFunctionName (std::string mangled)
Unmangle a function name.
Connection Manipulation
Functions for connecting and disconnecting nodes
Result connectData (NodeInstance &lhs, size_t lhsConnID, NodeInstance &rhs, size_t rhsConnID)
Connects two nodes' data connections.
Result connectExec (NodeInstance &lhs, size_t lhsConnID, NodeInstance &rhs, size_t rhsConnID)
Connects two nodes' exec connections.
Result disconnectData (NodeInstance &lhs, size_t lhsConnID, NodeInstance &rhs)
Disconnect a data connection.
Result disconnectExec (NodeInstance &lhs, size_t lhsConnID)
Disconnect a exec connection.
Detailed Description
The namespace where chigraph lives.
Enumeration Type Documentation
LoadSettings
enum chi::LoadSettings
Settings for loading modules.
Enumerator
Default
default, just load from disk
Fetch
fetch the repository that's being loaded
FetchRecursive
also fetch dependencies
Definition at line 33 of file Context.hpp.
VCSType
enum chi::VCSType strong
The Version Control Types.
Enumerator
Git
Git.
Definition at line 239 of file Context.hpp.
Function Documentation
compileFunction()
Result chi::compileFunction (const GraphFunction & func, llvm::Module * mod, llvm::DICompileUnit * debugCU, llvm::DIBuilder & debugBuilder)
Compile the graph to an llvm::Function (usually called from JsonModule::generateModule)
Parameters
func The function to compile
mod The module to codgen into, should already be a valid module
debugCU The compilation unit that the GraphFunction resides in.
debugBuilder The debug builder to build debug info
Returns
The result
Definition at line 279 of file FunctionCompiler.cpp.
References chi::Result::addEntry(), chi::GraphFunction::context(), chi::GraphModule::createLineNumberAssoc(), chi::GraphFunction::dataInputs(), chi::GraphFunction::dataOutputs(), chi::DataType::debugType(), chi::GraphFunction::entryNode(), chi::ChiModule::fullName(), chi::GraphFunction::functionType(), mangleFunctionName(), chi::GraphFunction::module(), chi::NamedDataType::name, chi::GraphFunction::name(), chi::NamedDataType::type, chi::Context::typeFromModule(), chi::DataType::valid(), and validateFunction().
Referenced by chi::GraphModule::generateModule().
connectData()
Result chi::connectData (NodeInstance & lhs, size_t lhsConnID, NodeInstance & rhs, size_t rhsConnID)
Connects two nodes' data connections.
Parameters
lhs The node to the left, the node outputting the data
lhsConnID The ID of data connection in lhs to be connected
rhs The node to the right, that takes in the data as a parameter
rhsConnID The ID of data input in rhs
Returns
The result
Definition at line 98 of file NodeInstance.cpp.
References chi::Result::addEntry(), chi::NodeType::dataInputs(), chi::NodeType::dataOutputs(), disconnectData(), chi::NodeInstance::function(), chi::NodeInstance::inputDataConnections, chi::NodeInstance::outputDataConnections, chi::NodeType::qualifiedName(), chi::NodeType::toJSON(), and chi::NodeInstance::type().
Referenced by jsonToGraphFunction(), and chi::NodeInstance::module().
connectExec()
Result chi::connectExec (NodeInstance & lhs, size_t lhsConnID, NodeInstance & rhs, size_t rhsConnID)
Connects two nodes' exec connections.
Parameters
lhs The node to the left, the node outputting the connections
lhsConnID The ID of exec connection in lhs to be connected
rhs The node to the right, that takes in the exec as a parameter
rhsConnID The ID of exec input in rhs
Returns
The result
Definition at line 158 of file NodeInstance.cpp.
References chi::Result::addEntry(), disconnectExec(), chi::NodeType::execInputs(), chi::NodeType::execOutputs(), chi::NodeInstance::function(), chi::NodeInstance::inputExecConnections, chi::NodeInstance::outputExecConnections, chi::NodeType::qualifiedName(), and chi::NodeInstance::type().
Referenced by jsonToGraphFunction(), and chi::NodeInstance::module().
createGraphFunctionDeclarationFromJson()
Result chi::createGraphFunctionDeclarationFromJson (GraphModule & createInside, const nlohmann::json & input, GraphFunction ** toFill = nullptr)
Create a forward declaration of a function in a module with an empty graph.
Parameters
createInside the GraphModule to create the forward declaration in
input The input JSON
Return values
toFill The GraphFunction* to fill, optional
Definition at line 97 of file JsonDeserializer.cpp.
References chi::Result::addEntry(), chi::ChiModule::context(), chi::ChiModule::fullName(), chi::GraphModule::getOrCreateFunction(), parseColonPair(), parseObjectPair(), chi::GraphFunction::setDescription(), and chi::Context::typeFromModule().
Referenced by jsonToGraphModule().
disconnectData()
Result chi::disconnectData (NodeInstance & lhs, size_t lhsConnID, NodeInstance & rhs)
Disconnect a data connection.
Parameters
lhs The left hand node
lhsConnID The ID of the data connection to disconnect
rhs The node that the data port is connected to
Returns
The result
Definition at line 203 of file NodeInstance.cpp.
References chi::Result::addEntry(), chi::NodeType::dataInputs(), chi::NodeType::dataOutputs(), chi::NodeInstance::function(), chi::NodeInstance::inputDataConnections, chi::NodeInstance::outputDataConnections, chi::NodeType::qualifiedName(), chi::NodeInstance::stringId(), chi::NodeType::toJSON(), and chi::NodeInstance::type().
Referenced by connectData(), chi::NodeInstance::module(), chi::GraphFunction::removeNode(), and chi::NodeInstance::setType().
disconnectExec()
Result chi::disconnectExec (NodeInstance & lhs, size_t lhsConnID)
Disconnect a exec connection.
Parameters
lhs The left hand node in the connection
lhsConnID The ID of the connection on lhs
Returns
The result
Definition at line 270 of file NodeInstance.cpp.
References chi::Result::addEntry(), chi::NodeType::execOutputs(), chi::NodeInstance::outputExecConnections, chi::NodeType::qualifiedName(), chi::NodeInstance::stringId(), and chi::NodeInstance::type().
Referenced by connectExec(), chi::NodeInstance::module(), chi::GraphFunction::removeNode(), and chi::NodeInstance::setType().
graphFunctionToJson()
nlohmann::json chi::graphFunctionToJson (const GraphFunction & func)
Serialize a GraphFunction to json.
Parameters
func The function to serialize
Returns
The serialized function
Definition at line 12 of file JsonSerializer.cpp.
References chi::GraphFunction::dataInputs(), chi::GraphFunction::dataOutputs(), chi::GraphFunction::description(), chi::GraphFunction::execInputs(), chi::GraphFunction::execOutputs(), chi::GraphFunction::localVariables(), chi::GraphFunction::name(), and chi::GraphFunction::nodes().
Referenced by graphModuleToJson().
graphModuleToJson()
nlohmann::json chi::graphModuleToJson (const GraphModule & mod)
Serialize a JsonModule to json.
Parameters
mod The module to serialize
Returns
The serialized module
Definition at line 94 of file JsonSerializer.cpp.
References chi::ChiModule::dependencies(), chi::GraphModule::functions(), graphFunctionToJson(), and graphStructToJson().
Referenced by chi::GraphModule::saveToDisk().
graphStructToJson()
nlohmann::json chi::graphStructToJson (const GraphStruct & struc)
Serialize a GraphStruct to json.
Parameters
struc The struct to serialize
Definition at line 112 of file JsonSerializer.cpp.
References chi::GraphStruct::types().
Referenced by graphModuleToJson().
interpretLLVMIR()
Result chi::interpretLLVMIR (std::unique_ptr< llvm::Module > mod, llvm::CodeGenOpt::Level optLevel = llvm::CodeGenOpt::Default, std::vector< llvm::GenericValue > args = {}, llvm::Function * funcToRun = nullptr, llvm::GenericValue * ret = nullptr)
Interpret LLVM IR, just a convenience function.
Parameters
[in] mod The LLVM Module to interpret
[in] optLevel How much the optimization should be applied. The default is roughly equilivant to -O2
[in] args The arguments to pass to the function, empty by default
[in] funcToRun The function to run. By default it uses "main".
[out] ret The GenericValue to fill with the result of the function. Optional
Definition at line 640 of file Context.cpp.
References chi::Result::addEntry().
Referenced by chi::Context::modules().
interpretLLVMIRAsMain()
Result chi::interpretLLVMIRAsMain (std::unique_ptr< llvm::Module > mod, llvm::CodeGenOpt::Level optLevel = llvm::CodeGenOpt::Default, std::vector< std::string > args = {}, llvm::Function * funcToRun = nullptr, int * ret = nullptr)
Interpret LLVM IR as if it were the main function.
Parameters
[in] mod The module to interpret
[in] optLevel The optimization level
[in] args The arguments to main
[in] funcToRun The function, defaults to "main" from mod
[out] ret The return from main. Optional.
Definition at line 674 of file Context.cpp.
References chi::Result::addEntry(), Git, and resolveUrlFromModuleName().
Referenced by chi::Context::modules().
jsonToGraphFunction()
Result chi::jsonToGraphFunction (GraphFunction & createInside, const nlohmann::json & input)
Load a GraphFunction–must already exist (use createGraphFunctionDeclarationFromJson)
Parameters
createInside The GraphFunction to create the graph for
input The JSON to load
Definition at line 208 of file JsonDeserializer.cpp.
References chi::Result::addEntry(), connectData(), connectExec(), chi::GraphFunction::context(), chi::GraphFunction::getOrCreateLocalVariable(), chi::GraphFunction::insertNode(), chi::GraphFunction::nodes(), chi::Context::nodeTypeFromModule(), parseColonPair(), and chi::Context::typeFromModule().
Referenced by jsonToGraphModule().
jsonToGraphModule()
Result chi::jsonToGraphModule (Context & createInside, const nlohmann::json & input, const boost::filesystem::path & fullName, GraphModule ** toFill = nullptr)
Load a GraphModule from json.
Parameters
createInside The Context to create the module in
input The JSON to load
fullName The full name of the module being loaded
Return values
toFill The GraphModule* to set, optional
Definition at line 11 of file JsonDeserializer.cpp.
References chi::Result::addEntry(), createGraphFunctionDeclarationFromJson(), jsonToGraphFunction(), jsonToGraphStruct(), and chi::Context::newGraphModule().
Referenced by chi::Context::addModuleFromJson().
jsonToGraphStruct()
Result chi::jsonToGraphStruct (GraphModule & mod, boost::string_view name, const nlohmann::json & input, GraphStruct ** toFill = nullptr)
Load a GraphStruct from json.
Parameters
mod The module to create it inside
input The JSON to load
Return values
toFill The object to fill, optional
Definition at line 426 of file JsonDeserializer.cpp.
References chi::Result::addEntry(), chi::ChiModule::context(), chi::GraphModule::getOrCreateStruct(), parseColonPair(), parseObjectPair(), and chi::Context::typeFromModule().
Referenced by jsonToGraphModule().
mangleFunctionName()
std::string chi::mangleFunctionName (std::string fullModuleName, const std::string & name)
Mangle a function name.
Parameters
fullModuleName The full name of the module. Example github.com/russelltg/test/lib
name The name of the function
Returns
The mangled name
Definition at line 8 of file NameMangler.cpp.
Referenced by compileFunction(), and chi::GraphModule::generateModule().
parseColonPair()
std::pair<std::string, std::string> chi::parseColonPair (const std::string & in) inline
Parse a colonated pair Example: lang:i32 would turn into {lang, i32}.
Parameters
in The colonated pair
Returns
{first, second}
Definition at line 347 of file GraphFunction.hpp.
References chi::GraphFunction::module(), and chi::GraphFunction::name().
Referenced by createGraphFunctionDeclarationFromJson(), jsonToGraphFunction(), jsonToGraphStruct(), chi::CModule::nodeTypeFromName(), and chi::GraphModule::nodeTypeFromName().
parseObjectPair()
std::pair< std::string, std::string > chi::parseObjectPair (const nlohmann::json & object)
Parse something that looks like: {"hello": "there"} into {"hello", "there"}.
Parameters
object The json object
Returns
{"key", "value"}
Definition at line 467 of file JsonDeserializer.cpp.
Referenced by createGraphFunctionDeclarationFromJson(), jsonToGraphStruct(), and chi::CModule::nodeTypeFromName().
resolveUrlFromModuleName()
std::tuple<VCSType, std::string, std::string> chi::resolveUrlFromModuleName (const boost::filesystem::path & path)
Get the URL for a VCS repository from a module name.
Parameters
path The module name
Returns
{The type of VCS that it is, the URL to clone, the relative path to clone to}
Referenced by chi::Context::fetchModule(), and interpretLLVMIRAsMain().
stringifyLLVMType()
std::string chi::stringifyLLVMType (llvm::Type * ty)
Turns a type into a string.
Parameters
ty The type to stringify
Returns
The return string
Definition at line 603 of file Context.cpp.
Referenced by chi::Context::modules(), and chi::CModule::nodeTypeFromName().
unmangleFunctionName()
std::pair< std::string, std::string > chi::unmangleFunctionName (std::string mangled)
Unmangle a function name.
Parameters
mangledName The mangled name
Returns
The unmangled name; {moduleName, functionName}
Definition at line 45 of file NameMangler.cpp.
Referenced by chi::Debugger::nodeFromFrame().
validateFunction()
Result chi::validateFunction (const GraphFunction & func)
Validate that a function is compilable.
If this succeeds, then it should be compilable Calls validateFunctionConnectionsAreTwoWay and validateFunctionNodeInputs
Parameters
func The function to check
Returns
The Result
Definition at line 12 of file FunctionValidator.cpp.
References validateFunctionConnectionsAreTwoWay(), validateFunctionExecOutputs(), and validateFunctionNodeInputs().
Referenced by compileFunction().
validateFunctionConnectionsAreTwoWay()
Result chi::validateFunctionConnectionsAreTwoWay (const GraphFunction & func)
Make sure that connections connect back and that they have the same types.
Parameters
func The function to check
Returns
The Result
Definition at line 21 of file FunctionValidator.cpp.
References chi::Result::addEntry(), chi::NodeInstance::inputDataConnections, chi::GraphFunction::nodes(), chi::NodeInstance::outputExecConnections, chi::NodeType::qualifiedName(), chi::NodeInstance::stringId(), and chi::NodeInstance::type().
Referenced by validateFunction().
validateFunctionExecOutputs()
Result chi::validateFunctionExecOutputs (const GraphFunction & func)
Make sure nodes have an output connection.
Parameters
func The function to check
Returns
The Result
Definition at line 207 of file FunctionValidator.cpp.
References chi::Result::addEntry(), and chi::GraphFunction::nodes().
Referenced by validateFunction().
validateFunctionNodeInputs()
Result chi::validateFunctionNodeInputs (const GraphFunction & func)
Make sure that nodes are called before their outputs are used.
Parameters
func The function to check
Returns
The Result
Definition at line 184 of file FunctionValidator.cpp.
References chi::GraphFunction::entryNode().
Referenced by validateFunction().
workspaceFromChildPath()
boost::filesystem::path chi::workspaceFromChildPath (const boost::filesystem::path & path)
Get the workspace directory from a child of the workspace directory Example: say you have a workspace at ~/chi/ If you used this with ~/chi/src/ it would return ~/chi/.
Parameters
path The child path
Returns
The workspace path, or an empty path if it wasn't found
Referenced by chi::Context::findInstancesOfType(), and chi::Context::modules().