chigraph: chig::JsonModule Struct Reference
chig::JsonModule Struct Reference
Module that holds JSON code.
#include <chig/JsonModule.hpp>
Public Member Functions
JsonModule (Context &cont, std::string fullName, const nlohmann::json &json_data, Result *res)
Constructor for a json module.
JsonModule (Context &cont, std::string fullName, gsl::span< std::string > dependencies)
Construct a JsonModule from scratch, no json.
JsonModule (const JsonModule &)=delete
JsonModule (JsonModule &&)=delete
Result addDependency (std::string newDepFullPath)
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Context & context () const
Get the Context that this module belongs to.
bool createFunction (gsl::cstring_span<> name, std::vector< std::pair< DataType, std::string >> dataIns, std::vector< std::pair< DataType, std::string >> dataOuts, std::vector< std::string > execIns, std::vector< std::string > execOuts, GraphFunction **toFill=nullptr)
Create a new function if it does't already exist.
boost::bimap< unsigned, NodeInstance * > createLineNumberAssoc () const
Create the associations from line number and function in debug info.
llvm::DIType * debugTypeFromName (gsl::cstring_span<>) override
Get the debug info for a type from the name.
const std::unordered_set< std::string > & dependencies () const
Get the dependencies.
std::string fullName () const
Get the full name of the module.
const std::vector< std::unique_ptr< GraphFunction > > & functions () const
Get functions.
Result generateModule (llvm::Module &module) override
Generate a llvm::Module from the module.
GraphFunction * graphFuncFromName (gsl::cstring_span<> name) const
Get a function from the name.
Result loadGraphs ()
Load the graphs (usually called by Context::addModule)
std::string name () const
Get the short name of the module (the last bit)
Result nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json &jsonData, std::unique_ptr< NodeType > *toFill) override
Create a node type that is in the module from the name and json.
std::vector< std::string > nodeTypeNames () const override
Get the possible node type names.
JsonModule & operator= (const JsonModule &)=delete
JsonModule & operator= (JsonModule &&)=delete
bool removeDependency (gsl::cstring_span<> depName)
Remove a dependency Does not unload from context.
bool removeFunction (gsl::cstring_span<> name)
Remove a function from the module.
void removeFunction (GraphFunction *func)
Remove a function from the module.
Result saveToDisk () const
Serialize to disk in the context.
boost::filesystem::path sourceFilePath () const
Get the path to the source file It's not garunteed to exist, because it could have not been saved.
Result toJSON (nlohmann::json *to_fill) const
Serialize to JSON.
DataType typeFromName (gsl::cstring_span<>) override
Get a DataType from the name.
std::vector< std::string > typeNames () const override
Get the possible DataType names.
Detailed Description
Module that holds JSON code.
Definition at line 28 of file JsonModule.hpp.
Constructor & Destructor Documentation
JsonModule() [1/2]
chig::JsonModule::JsonModule (Context & cont, std::string fullName, const nlohmann::json & json_data, Result * res)
Constructor for a json module.
Parameters
fullName Full path for the module
json_data The JSON
cont The context
res The result to fill if there are errors
Definition at line 93 of file JsonModule.cpp.
References chig::ChigModule::addDependency(), and chig::Result::addEntry().
JsonModule() [2/2]
chig::JsonModule::JsonModule (Context & cont, std::string fullName, gsl::span< std::string > dependencies)
Construct a JsonModule from scratch, no json.
Parameters
cont The context
fullName The full name of the module
dependencies The dependencies
Definition at line 145 of file JsonModule.cpp.
References chig::ChigModule::addDependency().
Member Function Documentation
addDependency()
Result chig::ChigModule::addDependency (std::string newDepFullPath) inherited
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Parameters
newDepFullPath The dependency, full path
Returns
The result
Definition at line 15 of file ChigModule.cpp.
References chig::ChigModule::context(), and chig::Context::loadModule().
Referenced by chig::ChigModule::dependencies(), and JsonModule().
context()
Context& chig::ChigModule::context () const inline inherited
Get the Context that this module belongs to.
Returns
The context
Definition at line 71 of file ChigModule.hpp.
References chig::ChigModule::generateModule().
Referenced by chig::ChigModule::addDependency(), chig::GraphFunction::GraphFunction(), chig::LangModule::LangModule(), chig::NodeType::NodeType(), saveToDisk(), sourceFilePath(), and chig::LangModule::typeFromName().
createFunction()
bool chig::JsonModule::createFunction (gsl::cstring_span<> name, std::vector< std::pair< DataType, std::string >> dataIns, std::vector< std::pair< DataType, std::string >> dataOuts, std::vector< std::string > execIns, std::vector< std::string > execOuts, GraphFunction ** toFill = nullptr)
Create a new function if it does't already exist.
Parameters
name The name of the new function
dataIns The data inputs to the function
dataOuts The data outputs to the function
execIns The exec inputs to the function
execOuts The exec outputs to the function
toFill The new GraphFunction, optional
Returns
True if a new function was created, false otherwise
Definition at line 229 of file JsonModule.cpp.
References graphFuncFromName().
Referenced by sourceFilePath().
createLineNumberAssoc()
boost::bimap< unsigned int, NodeInstance * > chig::JsonModule::createLineNumberAssoc () const
Create the associations from line number and function in debug info.
Returns
A bimap of function to line number
Definition at line 301 of file JsonModule.cpp.
References functions().
Referenced by chig::compileFunction(), and typeNames().
debugTypeFromName()
llvm::DIType* chig::JsonModule::debugTypeFromName (gsl::cstring_span<> name) inline override virtual
Get the debug info for a type from the name.
Parameters
name The name of the type
Returns
The DIType, or nullptr if failed
Implements chig::ChigModule.
Definition at line 55 of file JsonModule.hpp.
References nodeTypeNames().
dependencies()
const std::unordered_set<std::string>& chig::ChigModule::dependencies () const inline inherited
Get the dependencies.
Returns
The dependencies
Definition at line 79 of file ChigModule.hpp.
References chig::ChigModule::addDependency().
Referenced by toJSON().
fullName()
std::string chig::ChigModule::fullName () const inline inherited
Get the full name of the module.
Returns
The name
Definition at line 68 of file ChigModule.hpp.
Referenced by chig::Context::addModuleFromJson(), chig::compileFunction(), generateModule(), and sourceFilePath().
functions()
const std::vector<std::unique_ptr<GraphFunction> >& chig::JsonModule::functions () const inline
Get functions.
Returns
The functions
Definition at line 116 of file JsonModule.hpp.
Referenced by createLineNumberAssoc().
generateModule()
Result chig::JsonModule::generateModule (llvm::Module & module) override virtual
Generate a llvm::Module from the module.
Usually called by Context::compileModule
Parameters
module The llvm::Module to fill into – must be already filled with dependencies
Returns
The result
Implements chig::ChigModule.
Definition at line 151 of file JsonModule.cpp.
References chig::compileFunction(), chig::ChigModule::fullName(), chig::mangleFunctionName(), and sourceFilePath().
Referenced by typeNames().
graphFuncFromName()
GraphFunction * chig::JsonModule::graphFuncFromName (gsl::cstring_span<> name) const
Get a function from the name.
Parameters
name The name to get
Returns
The GraphFunction or nullptr if it doesn't exist
Definition at line 269 of file JsonModule.cpp.
References chig::ChigModule::name().
Referenced by createFunction(), nodeTypeFromName(), removeFunction(), and sourceFilePath().
name()
std::string chig::ChigModule::name () const inline inherited
Get the short name of the module (the last bit)
Returns
The name
Definition at line 65 of file ChigModule.hpp.
Referenced by graphFuncFromName(), chig::CModule::nodeTypeFromName(), nodeTypeFromName(), chig::DataType::qualifiedName(), chig::NodeType::qualifiedName(), and toJSON().
nodeTypeFromName()
Result chig::JsonModule::nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json & jsonData, std::unique_ptr< NodeType > * toFill) override virtual
Create a node type that is in the module from the name and json.
Parameters
name The name of the node type to create
jsonData The extra JSON data for the node
toFill The NodeType object to fill
Returns
The result
Implements chig::ChigModule.
Definition at line 277 of file JsonModule.cpp.
References chig::Result::addEntry(), graphFuncFromName(), and chig::ChigModule::name().
nodeTypeNames()
std::vector< std::string > chig::JsonModule::nodeTypeNames () const override virtual
Get the possible node type names.
Returns
A std::vector of the possible names
Implements chig::ChigModule.
Definition at line 293 of file JsonModule.cpp.
Referenced by debugTypeFromName().
removeDependency()
bool chig::ChigModule::removeDependency (gsl::cstring_span<> depName) inline inherited
Remove a dependency Does not unload from context.
Parameters
depName The name of the dependency to remove
Returns
If one was removed
Definition at line 90 of file ChigModule.hpp.
removeFunction() [1/2]
bool chig::JsonModule::removeFunction (gsl::cstring_span<> name)
Remove a function from the module.
Parameters
name The name of the function to remove
Returns
True if there was a function matching name that was removed
Definition at line 249 of file JsonModule.cpp.
References graphFuncFromName().
Referenced by sourceFilePath().
removeFunction() [2/2]
void chig::JsonModule::removeFunction (GraphFunction * func)
Remove a function from the module.
Parameters
func The function to remove
Definition at line 259 of file JsonModule.cpp.
saveToDisk()
Result chig::JsonModule::saveToDisk () const
Serialize to disk in the context.
Returns
The Result
Definition at line 195 of file JsonModule.cpp.
References chig::Result::addEntry(), chig::ChigModule::context(), sourceFilePath(), and toJSON().
Referenced by chig::Context::newJsonModule(), and typeNames().
sourceFilePath()
boost::filesystem::path chig::JsonModule::sourceFilePath () const inline
Get the path to the source file It's not garunteed to exist, because it could have not been saved.
Returns
The path
Definition at line 82 of file JsonModule.hpp.
References chig::ChigModule::context(), createFunction(), chig::ChigModule::fullName(), graphFuncFromName(), removeFunction(), and chig::Context::workspacePath().
Referenced by generateModule(), and saveToDisk().
toJSON()
Result chig::JsonModule::toJSON (nlohmann::json * to_fill) const
Serialize to JSON.
Parameters
to_fill The JSON to fill
Returns
The Result
Definition at line 175 of file JsonModule.cpp.
References chig::ChigModule::dependencies(), and chig::ChigModule::name().
Referenced by saveToDisk(), and typeNames().
typeFromName()
DataType chig::JsonModule::typeFromName (gsl::cstring_span<> name) inline override virtual
Get a DataType from the name.
Parameters
name The name of the type
Returns
The data type, or an invalid DataType if failed
Implements chig::ChigModule.
Definition at line 54 of file JsonModule.hpp.
The documentation for this struct was generated from the following files:
include/chig/JsonModule.hpp
src/JsonModule.cpp