chigraph: chi::FunctionCompiler Struct Reference
chi::FunctionCompiler Struct Reference
Class for compiling GraphFunctions into llvm::Functions.
#include <chi/FunctionCompiler.hpp>
Public Member Functions
FunctionCompiler (const GraphFunction &func, llvm::Module &moduleToGenInto, llvm::DICompileUnit &debugCU, llvm::DIBuilder &debugBuilder)
Constructor.
llvm::BasicBlock & allocBlock () const
The block for allocating variables at the beginning of the function.
Result compile ()
Generates the contents of the function.
bool compiled () const
Get if the function has been compiled (compile() has been called)
Context & context () const
Get function().context()
llvm::DISubroutineType * createSubroutineType ()
Create the subroutine type for the function.
llvm::DICompileUnit & debugCompileUnit () const
The compile unit for the module.
llvm::DIBuilder & diBuilder () const
The debug builder we're using for the module.
llvm::DISubprogram & diFunction () const
Get the debug function.
const GraphFunction & function () const
Get the graph function The GraphFunction.
NodeCompiler * getOrCreateNodeCompiler (NodeInstance &node)
Get or create a node compiler for a node.
Result initialize (bool validate=true)
Creates the function, but don't actually generate into it.
bool initialized () const
Get if the function is initialized (initialize() has been called)
llvm::Function & llFunction () const
Get the llvm function this compiler is generating.
llvm::Module & llvmModule () const
Get the module being generated.
llvm::Value * localVariable (boost::string_view name)
Get the value for a local variable.
GraphModule & module () const
Get function().module()
NodeCompiler * nodeCompiler (NodeInstance &node)
Get a node compile for a certain node.
int nodeLineNumber (NodeInstance &node)
Get the debug line number for the node instance Unique for each node.
llvm::Value & postPureBreak () const
Get the value for the address to jump back to.
Detailed Description
Class for compiling GraphFunctions into llvm::Functions.
Definition at line 21 of file FunctionCompiler.hpp.
Constructor & Destructor Documentation
FunctionCompiler()
chi::FunctionCompiler::FunctionCompiler (const GraphFunction & func, llvm::Module & moduleToGenInto, llvm::DICompileUnit & debugCU, llvm::DIBuilder & debugBuilder)
Constructor.
Parameters
func The function to compile
moduleToGenInto The module to create the function in
debugCU The compile unit we're in
debugBuilder The Debug information builder for the module
Definition at line 31 of file FunctionCompiler.cpp.
Member Function Documentation
allocBlock()
llvm::BasicBlock& chi::FunctionCompiler::allocBlock () const inline
The block for allocating variables at the beginning of the function.
Precondition
initialized() == true
Returns
The alloc block
Definition at line 72 of file FunctionCompiler.hpp.
References initialized(), and localVariable().
Referenced by compile().
compile()
Result chi::FunctionCompiler::compile ()
Generates the contents of the function.
Precondition
initialized() == true
compiled() == false
Postcondition
compiled() == true
Returns
The Result
Definition at line 199 of file FunctionCompiler.cpp.
References allocBlock(), compiled(), chi::dependentPuresRecursive(), chi::NodeCompiler::firstBlock(), getOrCreateNodeCompiler(), initialized(), and nodeCompiler().
compiled()
bool chi::FunctionCompiler::compiled () const inline
Get if the function has been compiled (compile() has been called)
Returns
True if it has, false otherwise
Definition at line 126 of file FunctionCompiler.hpp.
References chi::compileFunction(), getOrCreateNodeCompiler(), and nodeCompiler().
Referenced by compile().
context()
Context & chi::FunctionCompiler::context () const
Get function().context()
Returns
function().context()
Definition at line 341 of file FunctionCompiler.cpp.
Referenced by createSubroutineType(), and function().
createSubroutineType()
llvm::DISubroutineType * chi::FunctionCompiler::createSubroutineType ()
Create the subroutine type for the function.
Returns
The subroutine type
Definition at line 276 of file FunctionCompiler.cpp.
References context(), chi::Context::langModule(), chi::LangModule::typeFromName(), and chi::DataType::valid().
Referenced by initialize().
debugCompileUnit()
llvm::DICompileUnit& chi::FunctionCompiler::debugCompileUnit () const inline
The compile unit for the module.
Returns
The DICompileUnit
Definition at line 67 of file FunctionCompiler.hpp.
Referenced by initialize().
diBuilder()
llvm::DIBuilder& chi::FunctionCompiler::diBuilder () const inline
The debug builder we're using for the module.
Returns
The DIBuilder
Definition at line 63 of file FunctionCompiler.hpp.
Referenced by initialize(), and chi::NodeCompiler::NodeCompiler().
diFunction()
llvm::DISubprogram& chi::FunctionCompiler::diFunction () const inline
Get the debug function.
Precondition
initialized() == true
Returns
The debug function
Definition at line 51 of file FunctionCompiler.hpp.
References initialized().
getOrCreateNodeCompiler()
NodeCompiler * chi::FunctionCompiler::getOrCreateNodeCompiler (NodeInstance & node)
Get or create a node compiler for a node.
Precondition
&node.function() == &function()
Returns
The compiler.
Definition at line 363 of file FunctionCompiler.cpp.
References chi::NodeInstance::function().
Referenced by compile(), and compiled().
initialize()
Result chi::FunctionCompiler::initialize (bool validate = true)
Creates the function, but don't actually generate into it.
Precondition
initialized() == false
Postcondition
initialized() == true
Parameters
validate Should the module be validated (using functions in FunctionValidator.hpp)?
Returns
The Result
Definition at line 35 of file FunctionCompiler.cpp.
References chi::Result::addEntry(), chi::Result::addScopedContext(), chi::GraphModule::createLineNumberAssoc(), createSubroutineType(), debugCompileUnit(), diBuilder(), chi::ChiModule::fullName(), initialized(), llvmModule(), chi::mangleFunctionName(), module(), nodeLineNumber(), and chi::validateFunction().
initialized()
bool chi::FunctionCompiler::initialized () const inline
Get if the function is initialized (initialize() has been called)
Returns
True if it is, false otherwise
Definition at line 122 of file FunctionCompiler.hpp.
Referenced by allocBlock(), compile(), diFunction(), initialize(), llFunction(), localVariable(), and postPureBreak().
llFunction()
llvm::Function& chi::FunctionCompiler::llFunction () const inline
Get the llvm function this compiler is generating.
Precondition
initialized() == true
Returns
The function.
Definition at line 86 of file FunctionCompiler.hpp.
References initialized().
llvmModule()
llvm::Module& chi::FunctionCompiler::llvmModule () const inline
Get the module being generated.
Returns
The Module
Definition at line 59 of file FunctionCompiler.hpp.
Referenced by initialize(), and chi::NodeCompiler::llvmModule().
localVariable()
llvm::Value * chi::FunctionCompiler::localVariable (boost::string_view name)
Get the value for a local variable.
Precondition
initialized() == true
Returns
nullptr if it doesn't exist. A value if it's valid.
Definition at line 331 of file FunctionCompiler.cpp.
References initialized().
Referenced by allocBlock().
module()
GraphModule & chi::FunctionCompiler::module () const
Get function().module()
Returns
function().module()
Definition at line 340 of file FunctionCompiler.cpp.
Referenced by function(), and initialize().
nodeCompiler()
NodeCompiler * chi::FunctionCompiler::nodeCompiler (NodeInstance & node)
Get a node compile for a certain node.
Precondition
&node.function() == &function()
Returns
The node compiler for the function
Definition at line 354 of file FunctionCompiler.cpp.
References chi::NodeInstance::function().
Referenced by compile(), chi::NodeCompiler::compile_stage1(), and compiled().
nodeLineNumber()
int chi::FunctionCompiler::nodeLineNumber (NodeInstance & node)
Get the debug line number for the node instance Unique for each node.
Precondition
&node.function() == &function()
Parameters
node The instance to get the line number for
Returns
The line number
Definition at line 343 of file FunctionCompiler.cpp.
References chi::NodeInstance::function().
Referenced by function(), and initialize().
postPureBreak()
llvm::Value& chi::FunctionCompiler::postPureBreak () const inline
Get the value for the address to jump back to.
Precondition
initialized() == true
Returns
The value
Definition at line 95 of file FunctionCompiler.hpp.
References initialized().
The documentation for this struct was generated from the following files:
libchigraph/include/chi/FunctionCompiler.hpp
libchigraph/src/FunctionCompiler.cpp