chigraph: chig::ChigModule Struct Reference
chig::ChigModule Struct Reference abstract
An abstract class that represents a module of code in Chigraph Can be compiled to a llvm::Module.
#include <chig/ChigModule.hpp>
Public Member Functions
ChigModule (Context &contextArg, std::string moduleFullName)
Default constructor.
virtual ~ChigModule ()=default
Destructor.
Result addDependency (std::string newDepFullPath)
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Context & context () const
Get the Context that this module belongs to.
const std::unordered_set< std::string > & dependencies () const
Get the dependencies.
std::string fullName () const
Get the full name of the module.
virtual Result generateModule (llvm::Module &module)=0
Generate a llvm::Module from the module.
virtual Result nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json &jsonData, std::unique_ptr< NodeType > *toFill)=0
Create a node type that is in the module from the name and json.
virtual std::vector< std::string > nodeTypeNames () const =0
Get the possible node type names.
bool removeDependency (gsl::cstring_span<> depName)
Remove a dependency Does not unload from context.
std::string shortName () const
Get the short name of the module (the last bit)
virtual DataType typeFromName (gsl::cstring_span<> name)=0
Get a DataType from the name.
virtual std::vector< std::string > typeNames () const =0
Get the possible DataType names.
Detailed Description
An abstract class that represents a module of code in Chigraph Can be compiled to a llvm::Module.
Definition at line 23 of file ChigModule.hpp.
Constructor & Destructor Documentation
ChigModule()
chig::ChigModule::ChigModule (Context & contextArg, std::string moduleFullName)
Default constructor.
This is usually run by Context::loadModule
Parameters
contextArg The context to create the module insides
moduleFullName The full name of the module
Definition at line 8 of file ChigModule.cpp.
Member Function Documentation
addDependency()
Result chig::ChigModule::addDependency (std::string newDepFullPath)
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Parameters
newDepFullPath The dependency, full path
Returns
The result
Definition at line 15 of file ChigModule.cpp.
References context(), and chig::Context::loadModule().
Referenced by dependencies(), and chig::GraphModule::GraphModule().
context()
Context& chig::ChigModule::context () const inline
Get the Context that this module belongs to.
Returns
The context
Definition at line 60 of file ChigModule.hpp.
References generateModule().
Referenced by addDependency(), chig::createGraphFunctionDeclarationFromJson(), chig::jsonToGraphStruct(), chig::LangModule::LangModule(), chig::NodeType::NodeType(), chig::CModule::nodeTypeFromName(), chig::GraphModule::nodeTypeFromName(), chig::GraphModule::saveToDisk(), chig::GraphModule::sourceFilePath(), and chig::LangModule::typeFromName().
dependencies()
const std::unordered_set<std::string>& chig::ChigModule::dependencies () const inline
Get the dependencies.
Returns
The dependencies
Definition at line 68 of file ChigModule.hpp.
References addDependency().
Referenced by chig::graphModuleToJson().
fullName()
std::string chig::ChigModule::fullName () const inline
Get the full name of the module.
Returns
The name
Definition at line 57 of file ChigModule.hpp.
Referenced by chig::Context::addModuleFromJson(), chig::compileFunction(), chig::GraphModule::generateModule(), chig::CModule::nodeTypeFromName(), chig::GraphModule::nodeTypeFromName(), chig::DataType::qualifiedName(), chig::NodeType::qualifiedName(), and chig::GraphModule::sourceFilePath().
generateModule()
virtual Result chig::ChigModule::generateModule (llvm::Module & module) pure virtual
Generate a llvm::Module from the module.
Usually called by Context::compileModule
Parameters
module The llvm::Module to fill into – must be already filled with dependencies
Returns
The result
Implemented in chig::LangModule, chig::GraphModule, and chig::CModule.
Referenced by context().
nodeTypeFromName()
virtual Result chig::ChigModule::nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json & jsonData, std::unique_ptr< NodeType > * toFill) pure virtual
Create a node type that is in the module from the name and json.
Parameters
name The name of the node type to create
jsonData The extra JSON data for the node
toFill The NodeType object to fill
Returns
The result
Implemented in chig::GraphModule, chig::CModule, and chig::LangModule.
nodeTypeNames()
virtual std::vector<std::string> chig::ChigModule::nodeTypeNames () const pure virtual
Get the possible node type names.
Returns
A std::vector of the possible names
Implemented in chig::GraphModule, chig::CModule, and chig::LangModule.
removeDependency()
bool chig::ChigModule::removeDependency (gsl::cstring_span<> depName) inline
Remove a dependency Does not unload from context.
Parameters
depName The name of the dependency to remove
Returns
If one was removed
Definition at line 79 of file ChigModule.hpp.
shortName()
std::string chig::ChigModule::shortName () const inline
Get the short name of the module (the last bit)
Returns
The name
Definition at line 54 of file ChigModule.hpp.
Referenced by chig::graphModuleToJson().
typeFromName()
virtual DataType chig::ChigModule::typeFromName (gsl::cstring_span<> name) pure virtual
Get a DataType from the name.
Parameters
name The name of the type
Returns
The data type, or an invalid DataType if failed
Implemented in chig::GraphModule, chig::CModule, and chig::LangModule.
Referenced by chig::Context::typeFromModule().
The documentation for this struct was generated from the following files:
include/chig/ChigModule.hpp
src/ChigModule.cpp