chigraph: chig::DataType Struct Reference
chig::DataType Struct Reference
A type of data Loose wrapper around llvm::Type*, except it knows which ChigModule it's in and it embeds debug types.
#include <chig/DataType.hpp>
Public Member Functions
DataType (ChigModule *chigMod=nullptr, std::string typeName={}, llvm::Type *llvmtype=nullptr, llvm::DIType *debugTy=nullptr)
Constructor.
llvm::DIType * debugType () const
Get the debug type.
llvm::Type * llvmType () const
Get the underlying llvm::Type.
ChigModule & module () const
Get the module this is a part of.
std::string qualifiedName () const
Get the qualified name of the type (module().fullName() + ":" name())
const std::string & unqualifiedName () const
Get the unqualified name of the type.
bool valid () const
Check if the DataType is valid (if it's actually bound to a type and module)
Related Functions
(Note that these are not member functions.)
bool operator!= (const DataType &lhs, const DataType &rhs)
Inequality check.
bool operator== (const DataType &lhs, const DataType &rhs)
Equality check.
Detailed Description
A type of data Loose wrapper around llvm::Type*, except it knows which ChigModule it's in and it embeds debug types.
Definition at line 17 of file DataType.hpp.
Constructor & Destructor Documentation
DataType()
chig::DataType::DataType (ChigModule * chigMod = nullptr, std::string typeName = {}, llvm::Type * llvmtype = nullptr, llvm::DIType * debugTy = nullptr) inline
Constructor.
Parameters
chigMod The module
typeName The ID of the type in the module
llvmtype The underlying type
Definition at line 22 of file DataType.hpp.
Member Function Documentation
debugType()
llvm::DIType* chig::DataType::debugType () const inline
Get the debug type.
Returns
The debug type
Definition at line 40 of file DataType.hpp.
Referenced by chig::compileFunction(), and operator==().
llvmType()
llvm::Type* chig::DataType::llvmType () const inline
Get the underlying llvm::Type.
Returns
the llvm::Type
Definition at line 37 of file DataType.hpp.
Referenced by operator==().
module()
ChigModule& chig::DataType::module () const inline
Get the module this is a part of.
Returns
The module
Definition at line 28 of file DataType.hpp.
Referenced by operator==(), and qualifiedName().
qualifiedName()
std::string chig::DataType::qualifiedName () const inline
Get the qualified name of the type (module().fullName() + ":" name())
Returns
The qualified name
Definition at line 34 of file DataType.hpp.
References chig::ChigModule::fullName(), module(), and unqualifiedName().
Referenced by chig::GraphFunction::retypeLocalVariable().
unqualifiedName()
const std::string& chig::DataType::unqualifiedName () const inline
Get the unqualified name of the type.
Returns
The unqualified name
Definition at line 31 of file DataType.hpp.
Referenced by operator==(), and qualifiedName().
Friends And Related Function Documentation
operator!=()
bool operator!= (const DataType & lhs, const DataType & rhs) related
Inequality check.
Parameters
lhs The first DataType
rhs The DataType to check equality against
Returns
If they aren't equal
Definition at line 68 of file DataType.hpp.
operator==()
bool operator== (const DataType & lhs, const DataType & rhs) related
Equality check.
Parameters
lhs The first DataType
rhs The DataType to check equality against
Returns
If they are equal
Definition at line 58 of file DataType.hpp.
References debugType(), llvmType(), module(), and unqualifiedName().
The documentation for this struct was generated from the following file:
libchig/include/chig/DataType.hpp