chigraph: chig::Graph Struct Reference
chig::Graph Struct Reference
A graph holding nodes Normally not used by the user, used through GraphFunction.
#include <chig/Graph.hpp>
Public Member Functions
Graph (GraphFunction &func)
Default constructor, creates an empty graph.
Graph (GraphFunction &func, const nlohmann::json &data, Result &res)
Normal constructor (don't call this, let GraphFunction call it)
Context & context () const
Get the context.
Result insertNode (std::unique_ptr< NodeType > type, float x, float y, gsl::cstring_span<> id, NodeInstance **toFill=nullptr)
Add a node to the graph.
std::unordered_map< std::string, std::unique_ptr< NodeInstance > > & nodes ()
Get the nodes in the function Usually called by connectData or connectExec or GraphFunction.
const std::unordered_map< std::string, std::unique_ptr< NodeInstance > > & nodes () const
Get the nodes in the function Usually called by connectData or connectExec or GraphFunction.
std::vector< NodeInstance * > nodesWithType (gsl::cstring_span<> module, gsl::cstring_span<> name) const noexcept
Gets the nodes with a given type.
Result toJson (nlohmann::json *toFill) const
Convert to JSON.
Detailed Description
A graph holding nodes Normally not used by the user, used through GraphFunction.
Definition at line 23 of file Graph.hpp.
Constructor & Destructor Documentation
Graph()
Graph::Graph (GraphFunction & func, const nlohmann::json & data, Result & res)
Normal constructor (don't call this, let GraphFunction call it)
Parameters
func The context object
data The JSON data
res The result to fill in the case of errors
Definition at line 10 of file Graph.cpp.
References chig::Result::addEntry(), chig::connectData(), chig::connectExec(), context(), chig::GraphFunction::context(), insertNode(), chig::Context::nodeTypeFromModule(), and chig::parseColonPair().
Member Function Documentation
context()
Context& chig::Graph::context () const inline
Get the context.
Returns
The context
Definition at line 57 of file Graph.hpp.
Referenced by Graph().
insertNode()
Result Graph::insertNode (std::unique_ptr< NodeType > type, float x, float y, gsl::cstring_span<> id, NodeInstance ** toFill = nullptr)
Add a node to the graph.
Parameters
type The type of the node
x The x location of the node
y The y location of the node
id The node ID
toFill The NodeInstance object to fill into, optional
Returns
The Result.
Definition at line 195 of file Graph.cpp.
References chig::Result::addEntry(), and nodes().
Referenced by Graph(), and chig::GraphFunction::insertNode().
nodes() [1/2]
std::unordered_map<std::string, std::unique_ptr<NodeInstance> >& chig::Graph::nodes () inline
Get the nodes in the function Usually called by connectData or connectExec or GraphFunction.
Returns
The nodes, mapped by id, value
Definition at line 61 of file Graph.hpp.
Referenced by insertNode(), chig::GraphFunction::removeNode(), and chig::validateFunctionConnectionsAreTwoWay().
nodes() [2/2]
const std::unordered_map<std::string, std::unique_ptr<NodeInstance> >& chig::Graph::nodes () const inline
Get the nodes in the function Usually called by connectData or connectExec or GraphFunction.
Returns
The nodes, mapped by id, value
Definition at line 63 of file Graph.hpp.
nodesWithType()
std::vector< NodeInstance * > Graph::nodesWithType (gsl::cstring_span<> module, gsl::cstring_span<> name) const noexcept
Gets the nodes with a given type.
Parameters
module The module the type is in
name The name of the type
Returns
A vector of NodeInstance
Definition at line 215 of file Graph.cpp.
Referenced by chig::GraphFunction::entryNode(), and chig::GraphFunction::modifyExecOutput().
toJson()
Result Graph::toJson (nlohmann::json * toFill) const
Convert to JSON.
Don't actually call this, let GraphFunction
Parameters
toFill The JSON object to fill.
Returns
The result
Definition at line 150 of file Graph.cpp.
Referenced by chig::GraphFunction::toJSON().
The documentation for this struct was generated from the following files:
include/chig/Graph.hpp
src/Graph.cpp