chigraph: chi::NodeType Struct Reference
chi::NodeType Struct Reference abstract
A generic node type.
#include <chi/NodeType.hpp>
Public Member Functions
NodeType (ChiModule &mod, std::string name={}, std::string description={})
Constructor.
virtual ~NodeType ()
Destructor.
virtual std::unique_ptr< NodeType > clone () const =0
Clones the type.
virtual Result codegen (NodeCompiler &compiler, llvm::BasicBlock &codegenInto, size_t execInputID, const llvm::DebugLoc &nodeLocation, const std::vector< llvm::Value *> &io, const std::vector< llvm::BasicBlock *> &outputBlocks)=0
A virtual function that is called when this node needs to be called.
Context & context () const
Get the Context this NodeType belongs to.
bool converter ()
Get if this node is a converter.
const std::vector< NamedDataType > & dataInputs () const
Get the data inputs for the node.
const std::vector< NamedDataType > & dataOutputs () const
Get the data outputs for the node.
std::string description () const
Get the description of the NodeType.
const std::vector< std::string > & execInputs () const
Get the execution inputs for the node.
const std::vector< std::string > & execOutputs () const
Get the execution outputs for the node.
ChiModule & module () const
Get the ChiModule this NodeType belongs to.
std::string name () const
Get the name of the NodeType in the ChiModule.
bool pure ()
Get if this node is pure.
std::string qualifiedName () const
Get the qualified name of the node type, like module.name():name()
virtual nlohmann::json toJSON () const
Create the JSON necessary to store the object.
Protected Member Functions
void makeConverter ()
Make this a converter node.
void makePure ()
Make this node pure For more info on what this means, see https://en.wikipedia.org/wiki/Pure_function Also, UE4 implements it https://docs.unrealengine.com/latest/INT/Engine/Blueprints/UserGuide/Functions/#purevsstopimpure Pure nodes only have no inexecs and no outexecs When they are called they are backpropagated and all called They should usually be cheap and sideaffectless.
NodeInstance * nodeInstance () const
Get the node instance.
void setDataInputs (std::vector< NamedDataType > newInputs)
Set the data inputs for the NodeType.
void setDataOutputs (std::vector< NamedDataType > newOutputs)
Set the data outputs for the NodeType.
void setDescription (std::string newDesc)
Set the description of the node.
void setExecInputs (std::vector< std::string > newInputs)
Set the exec inputs for the NodeType.
void setExecOutputs (std::vector< std::string > newOutputs)
Set the exec outputs for the NodeType.
void setName (std::string newName)
Set the name of the type.
Detailed Description
A generic node type.
All user made types are of JsonNo deType type, which is defined in JsonModule.cpp. This allows for easy extension of the language.
Definition at line 19 of file NodeType.hpp.
Constructor & Destructor Documentation
NodeType()
chi::NodeType::NodeType (ChiModule & mod, std::string name = {}, std::string description = {})
Constructor.
Parameters
mod The module to create the NodeType in
name The name of the NodeType
description The description of the NodeType
Definition at line 9 of file NodeType.cpp.
References description(), name(), and ~NodeType().
Member Function Documentation
clone()
virtual std::unique_ptr<NodeType> chi::NodeType::clone () const pure virtual
Clones the type.
Returns
The clone
Referenced by toJSON().
codegen()
virtual Result chi::NodeType::codegen (NodeCompiler & compiler, llvm::BasicBlock & codegenInto, size_t execInputID, const llvm::DebugLoc & nodeLocation, const std::vector< llvm::Value *> & io, const std::vector< llvm::BasicBlock *> & outputBlocks) pure virtual
A virtual function that is called when this node needs to be called.
Parameters
compiler The compiler
execInputID The ID of the exec input
nodeLocation The location of the node
io This has the values that are the inputs and outputs of the function. This vector will always have the size of inputs.size() + outputs.size() and starts with the inputs. The types are gaurenteed to be the same as inputs and outputs
outputBlocks The blocks that can be outputted. This will be the same size as numOutputExecs.
Returns
The Result
Referenced by chi::NodeCompiler::compile_stage2().
context()
Context& chi::NodeType::context () const inline
Get the Context this NodeType belongs to.
Returns
The Context
Definition at line 70 of file NodeType.hpp.
dataInputs()
const std::vector<NamedDataType>& chi::NodeType::dataInputs () const inline
Get the data inputs for the node.
Returns
The data inputs in the format of {{DataType, description}, ...}
Definition at line 73 of file NodeType.hpp.
Referenced by chi::NodeCompiler::compile_stage2(), chi::connectData(), chi::disconnectData(), makeConverter(), and chi::NodeInstance::setType().
dataOutputs()
const std::vector<NamedDataType>& chi::NodeType::dataOutputs () const inline
Get the data outputs for the node.
Returns
The data outputs in the format of {{DataType, description}, ...}
Definition at line 76 of file NodeType.hpp.
Referenced by chi::connectData(), chi::disconnectData(), makeConverter(), chi::NodeCompiler::NodeCompiler(), and chi::NodeInstance::setType().
description()
std::string chi::NodeType::description () const inline
Get the description of the NodeType.
Returns
The description
Definition at line 64 of file NodeType.hpp.
Referenced by NodeType().
execInputs()
const std::vector<std::string>& chi::NodeType::execInputs () const inline
Get the execution inputs for the node.
Returns
The names of the inputs. The size of this vector is the size of inputs.
Definition at line 79 of file NodeType.hpp.
Referenced by chi::connectExec().
execOutputs()
const std::vector<std::string>& chi::NodeType::execOutputs () const inline
Get the execution outputs for the node.
Returns
The names of the outputs. The size is the input count.
Definition at line 82 of file NodeType.hpp.
Referenced by chi::connectExec(), and chi::disconnectExec().
makeConverter()
void chi::NodeType::makeConverter () protected
Make this a converter node.
Precondition
pure() == true Allows for this node to be created automatically for conversions
Definition at line 44 of file NodeType.cpp.
References dataInputs(), dataOutputs(), and pure().
Referenced by converter().
module()
ChiModule& chi::NodeType::module () const inline
Get the ChiModule this NodeType belongs to.
Returns
The ChiModule
Definition at line 67 of file NodeType.hpp.
Referenced by qualifiedName().
name()
std::string chi::NodeType::name () const inline
Get the name of the NodeType in the ChiModule.
Returns
The name
Definition at line 61 of file NodeType.hpp.
Referenced by NodeType(), and qualifiedName().
nodeInstance()
NodeInstance * chi::NodeType::nodeInstance () const protected
Get the node instance.
Returns
the node instance
Definition at line 52 of file NodeType.cpp.
Referenced by converter().
pure()
bool chi::NodeType::pure () inline
Get if this node is pure.
Returns
If it's pure
Definition at line 86 of file NodeType.hpp.
Referenced by makeConverter(), and chi::NodeCompiler::pure().
qualifiedName()
std::string chi::NodeType::qualifiedName () const
Get the qualified name of the node type, like module.name():name()
Returns
The qualified name
Definition at line 17 of file NodeType.cpp.
References chi::ChiModule::fullName(), module(), and name().
Referenced by chi::connectData(), chi::connectExec(), chi::disconnectData(), chi::disconnectExec(), and chi::validateFunctionConnectionsAreTwoWay().
setDataInputs()
void chi::NodeType::setDataInputs (std::vector< NamedDataType > newInputs) protected
Set the data inputs for the NodeType.
Parameters
newInputs The new inputs
Definition at line 19 of file NodeType.cpp.
Referenced by converter().
setDataOutputs()
void chi::NodeType::setDataOutputs (std::vector< NamedDataType > newOutputs) protected
Set the data outputs for the NodeType.
Parameters
newOutputs The new outputs
Definition at line 24 of file NodeType.cpp.
Referenced by converter().
setDescription()
void chi::NodeType::setDescription (std::string newDesc) protected
Set the description of the node.
Parameters
newDesc The new description
Definition at line 56 of file NodeType.cpp.
Referenced by converter().
setExecInputs()
void chi::NodeType::setExecInputs (std::vector< std::string > newInputs) protected
Set the exec inputs for the NodeType.
Parameters
newInputs The new inputs
Definition at line 29 of file NodeType.cpp.
Referenced by converter(), and makePure().
setExecOutputs()
void chi::NodeType::setExecOutputs (std::vector< std::string > newOutputs) protected
Set the exec outputs for the NodeType.
Parameters
newOutputs The new outputs
Definition at line 33 of file NodeType.cpp.
Referenced by converter(), and makePure().
setName()
void chi::NodeType::setName (std::string newName) protected
Set the name of the type.
Parameters
newName The new name
Definition at line 54 of file NodeType.cpp.
Referenced by converter().
toJSON()
virtual nlohmann::json chi::NodeType::toJSON () const inline virtual
Create the JSON necessary to store the object.
Returns
The json obejct
Definition at line 54 of file NodeType.hpp.
References clone().
Referenced by chi::connectData(), and chi::disconnectData().
The documentation for this struct was generated from the following files:
lib/core/include/chi/NodeType.hpp
lib/core/src/NodeType.cpp