chigraph: chi::GraphFunction Struct Reference
chi::GraphFunction Struct Reference
this is an AST-like representation of a function in a graph It is used for IDE-like behavior, codegen, and JSON generation.
#include <chi/GraphFunction.hpp>
Public Member Functions
GraphFunction (GraphModule &mod, std::string name, std::vector< NamedDataType > dataIns, std::vector< NamedDataType > dataOuts, std::vector< std::string > execIns, std::vector< std::string > execOuts)
Construct a graph–don't call this directly use GraphModule::getorCreateFunction.
GraphFunction (const GraphFunction &)=delete
GraphFunction (GraphFunction &&)=delete
~GraphFunction ()=default
Destructor.
Context & context () const
Get the context.
Result createEntryNodeType (std::unique_ptr< NodeType > *toFill) const
Create a fresh NodeType for an entry.
Result createExitNodeType (std::unique_ptr< NodeType > *toFill) const
Create a fresh NodeType for an exit.
const std::string & description () const
Get the description of the function.
llvm::FunctionType * functionType () const
Get the LLVM function type for the function.
GraphModule & module () const
Get the GraphModule that contains this GraphFunction.
std::string name () const
Get the name of the function.
GraphFunction & operator= (const GraphFunction &)=delete
GraphFunction & operator= (GraphFunction &&)=delete
void setDescription (std::string newDesc)
Set the description of the function.
Node Manipulation
Functions for mainpulating nodes; getting, adding
std::unordered_map< boost::uuids::uuid, std::unique_ptr< NodeInstance > > & nodes ()
Get the nodes in the function Usually called by connectData or connectExec or GraphFunction.
const std::unordered_map< boost::uuids::uuid, std::unique_ptr< NodeInstance > > & nodes () const
NodeInstance * nodeByID (const boost::uuids::uuid &id) const
Get a node with a given ID.
NodeInstance * entryNode () const noexcept
Gets the node with type lang:entry returns nullptr on failure Also returns nullptr if there are two entry nodes, which is illegal.
Result insertNode (std::unique_ptr< NodeType > type, float x, float y, boost::uuids::uuid id=boost::uuids::random_generator()(), NodeInstance **toFill=nullptr)
Add a node to the graph.
std::vector< NodeInstance * > nodesWithType (const boost::filesystem::path &module, boost::string_view name) const noexcept
Gets the nodes with a given type.
Result insertNode (const boost::filesystem::path &moduleName, boost::string_view typeName, const nlohmann::json &typeJSON, float x, float y, boost::uuids::uuid id=boost::uuids::random_generator()(), NodeInstance **toFill=nullptr)
Add a node to the graph using module, type, and json.
Result removeNode (NodeInstance *nodeToRemove)
Remove a node from the function.
Result getOrInsertEntryNode (float x, float y, boost::uuids::uuid id=boost::uuids::random_generator()(), NodeInstance **toFill=nullptr)
Creates an entry node if it doesn't already exist, else just return it.
Data input modifiers
const std::vector< NamedDataType > & dataInputs () const
Get the function data inputs in the format {type, docstring}.
void addDataInput (const DataType &type, std::string name, size_t addBefore=(std::numeric_limits< size_t >::max)())
Add an input to the end of the argument list.
void removeDataInput (size_t idx)
Remove an input from the argument list Also removes invalid connections If idx is out of range, this function does nothing.
void renameDataInput (size_t idx, std::string newName)
Rename a data input This also updates the entry node If idx is out of range, this function does nothing.
void retypeDataInput (size_t idx, DataType newType)
Change the type of a data input This also updates the entry node and disconnects invalid connections.
Data output modifiers
const std::vector< NamedDataType > & dataOutputs () const
Get the function data outputs in the format {type, docstring}.
void addDataOutput (const DataType &type, std::string name, size_t addBefore=(std::numeric_limits< size_t >::max)())
Add an data output to the end of the argument list.
void removeDataOutput (size_t idx)
Remove an data output from the argument list Also removes invalid connections If idx is out of range, this function does nothing.
void renameDataOutput (size_t idx, std::string newName)
Modify an data output (change it's type and docstring)
void retypeDataOutput (size_t idx, DataType newType)
Change the type of a data output This also updates all exit nodes and disconnects invalid connections.
Exec input modifiers
const std::vector< std::string > & execInputs () const
Get the function exec inputs.
void addExecInput (std::string name, size_t addBefore=(std::numeric_limits< size_t >::max)())
Add an exec input to the end of the argument list.
void removeExecInput (size_t idx)
Remove an exec input from the argument list If idx is out of range, this function does nothing.
void renameExecInput (size_t idx, std::string name)
Change the name for an exec input If idx is out of range, this function does nothing.
Exec output modifiers
Getters/modifers for exec output
const std::vector< std::string > & execOutputs () const
Get the function exec outputs.
void addExecOutput (std::string name, size_t addBefore=(std::numeric_limits< size_t >::max)())
Add an exec output to the end of the argument list.
void removeExecOutput (size_t idx)
Remove an exec output from the argument list If idx is out of range, this function does nothing.
void renameExecOutput (size_t idx, std::string name)
Rename an exec output If idx is out of range, this function does nothing.
Local Variable Manipulation functions
const std::vector< NamedDataType > & localVariables () const
Get the local variables.
NamedDataType localVariableFromName (boost::string_view name) const
Get a local varaible by name.
NamedDataType getOrCreateLocalVariable (std::string name, DataType type, bool *inserted=nullptr)
Create a new local varaible in the module.
bool removeLocalVariable (boost::string_view name)
Remove a local variable from the function by name.
void renameLocalVariable (std::string oldName, std::string newName)
Rename a local variable.
void retypeLocalVariable (boost::string_view name, DataType newType)
Set a new type to a local variable.
Detailed Description
this is an AST-like representation of a function in a graph It is used for IDE-like behavior, codegen, and JSON generation.
Definition at line 27 of file GraphFunction.hpp.
Constructor & Destructor Documentation
GraphFunction()
chi::GraphFunction::GraphFunction (GraphModule & mod, std::string name, std::vector< NamedDataType > dataIns, std::vector< NamedDataType > dataOuts, std::vector< std::string > execIns, std::vector< std::string > execOuts)
Construct a graph–don't call this directly use GraphModule::getorCreateFunction.
Parameters
mod The owning module
name The name of the function
dataIns The data inputs to the function
dataOuts The data outputs of the function
execIns The exec inputs to the function
execOuts The exec outputs to the function
Definition at line 20 of file GraphFunction.cpp.
References name().
Member Function Documentation
addDataInput()
void chi::GraphFunction::addDataInput (const DataType & type, std::string name, size_t addBefore = (std::numeric_limits<size_t>::max)())
Add an input to the end of the argument list.
Parameters
type The new input type
name The name of the input (just for documentation)
addBefore The input ID to add before, default is end
Definition at line 197 of file GraphFunction.cpp.
Referenced by dataInputs().
addDataOutput()
void chi::GraphFunction::addDataOutput (const DataType & type, std::string name, size_t addBefore = (std::numeric_limits<size_t>::max)())
Add an data output to the end of the argument list.
Parameters
type The new output type
name The name of the output (just for documentation)
addBefore The output to add before, default is end
Definition at line 221 of file GraphFunction.cpp.
Referenced by dataOutputs().
addExecInput()
void chi::GraphFunction::addExecInput (std::string name, size_t addBefore = (std::numeric_limits<size_t>::max)())
Add an exec input to the end of the argument list.
Parameters
name The name of the input (just for documentation)
addBefore the input to add after
Definition at line 265 of file GraphFunction.cpp.
Referenced by execInputs().
addExecOutput()
void chi::GraphFunction::addExecOutput (std::string name, size_t addBefore = (std::numeric_limits<size_t>::max)())
Add an exec output to the end of the argument list.
Parameters
name The name of the output (just for documentation)
addBefore The output to add after
Definition at line 285 of file GraphFunction.cpp.
Referenced by execOutputs().
context()
Context& chi::GraphFunction::context () const inline
Get the context.
Returns
The context
Definition at line 314 of file GraphFunction.hpp.
Referenced by chi::compileFunction(), createEntryNodeType(), createExitNodeType(), functionType(), insertNode(), and chi::jsonToGraphFunction().
createEntryNodeType()
Result chi::GraphFunction::createEntryNodeType (std::unique_ptr< NodeType > * toFill) const
Create a fresh NodeType for an entry.
Return values
toFill The NodeType pointer to fill
Precondition
toFill isn't null (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The result
Definition at line 144 of file GraphFunction.cpp.
References context(), dataInputs(), execInputs(), and chi::Context::nodeTypeFromModule().
Referenced by getOrInsertEntryNode(), nodes(), and renameExecOutput().
createExitNodeType()
Result chi::GraphFunction::createExitNodeType (std::unique_ptr< NodeType > * toFill) const
Create a fresh NodeType for an exit.
Return values
toFill The NodeType pointer to fill
Precondition
toFill isn't null (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The result
Definition at line 162 of file GraphFunction.cpp.
References context(), dataOutputs(), execOutputs(), and chi::Context::nodeTypeFromModule().
Referenced by nodes(), and renameExecOutput().
dataInputs()
const std::vector<NamedDataType>& chi::GraphFunction::dataInputs () const inline
Get the function data inputs in the format {type, docstring}.
Returns
The inputs
Definition at line 149 of file GraphFunction.hpp.
References addDataInput(), removeDataInput(), renameDataInput(), and retypeDataInput().
Referenced by chi::compileFunction(), createEntryNodeType(), entryNode(), functionType(), and chi::graphFunctionToJson().
dataOutputs()
const std::vector<NamedDataType>& chi::GraphFunction::dataOutputs () const inline
Get the function data outputs in the format {type, docstring}.
Returns
The outputs
Definition at line 184 of file GraphFunction.hpp.
References addDataOutput(), removeDataOutput(), renameDataOutput(), and retypeDataOutput().
Referenced by chi::compileFunction(), createExitNodeType(), functionType(), and chi::graphFunctionToJson().
description()
const std::string& chi::GraphFunction::description () const inline
Get the description of the function.
Returns
The description
Definition at line 307 of file GraphFunction.hpp.
Referenced by chi::graphFunctionToJson().
entryNode()
NodeInstance * chi::GraphFunction::entryNode () const noexcept
Gets the node with type lang:entry returns nullptr on failure Also returns nullptr if there are two entry nodes, which is illegal.
Returns
the entry node
Definition at line 41 of file GraphFunction.cpp.
References dataInputs(), execInputs(), and nodesWithType().
Referenced by chi::compileFunction(), getOrInsertEntryNode(), nodes(), and chi::validateFunctionNodeInputs().
execInputs()
const std::vector<std::string>& chi::GraphFunction::execInputs () const inline
Get the function exec inputs.
Returns
The exec outputs
Definition at line 220 of file GraphFunction.hpp.
References addExecInput(), removeExecInput(), and renameExecInput().
Referenced by createEntryNodeType(), entryNode(), and chi::graphFunctionToJson().
execOutputs()
const std::vector<std::string>& chi::GraphFunction::execOutputs () const inline
Get the function exec outputs.
Returns
The exec outputs
Definition at line 245 of file GraphFunction.hpp.
References addExecOutput(), removeExecOutput(), and renameExecOutput().
Referenced by createExitNodeType(), and chi::graphFunctionToJson().
functionType()
llvm::FunctionType * chi::GraphFunction::functionType () const
Get the LLVM function type for the function.
Returns
The function type
Definition at line 247 of file GraphFunction.cpp.
References context(), dataInputs(), and dataOutputs().
Referenced by chi::compileFunction(), and nodes().
getOrCreateLocalVariable()
NamedDataType chi::GraphFunction::getOrCreateLocalVariable (std::string name, DataType type, bool * inserted = nullptr)
Create a new local varaible in the module.
Parameters
name The name of the local variable
type The type of the local
inserted True if the local varaiable was new, optional
Returns
The new local variable or the already existing one
Definition at line 335 of file GraphFunction.cpp.
References localVariableFromName().
Referenced by chi::jsonToGraphFunction(), and localVariables().
getOrInsertEntryNode()
Result chi::GraphFunction::getOrInsertEntryNode (float x, float y, boost::uuids::uuid id = boost::uuids::random_generator()(), NodeInstance ** toFill = nullptr)
Creates an entry node if it doesn't already exist, else just return it.
Parameters
x The x coordinate of the new entry, or changes the existing entry node to be at this X location
y The y coordinate of the new entry, or changes the existing entry node to be at this Y location
id The ID of the node, disregarded if there is already an entry
Return values
toFill The NodeInstance* to fill, optional
Returns
The Result
Definition at line 180 of file GraphFunction.cpp.
References createEntryNodeType(), entryNode(), and insertNode().
Referenced by nodes().
insertNode() [1/2]
Result chi::GraphFunction::insertNode (std::unique_ptr< NodeType > type, float x, float y, boost::uuids::uuid id = boost::uuids::random_generator()(), NodeInstance ** toFill = nullptr)
Add a node to the graph.
Parameters
type The type of the node
x The x location of the node
y The y location of the node
id The node ID
Return values
toFill The nodeInstance to fill to, optional.
Returns
The result
Definition at line 61 of file GraphFunction.cpp.
References chi::Result::addEntry(), and nodes().
Referenced by getOrInsertEntryNode(), chi::jsonToGraphFunction(), and nodes().
insertNode() [2/2]
Result chi::GraphFunction::insertNode (const boost::filesystem::path & moduleName, boost::string_view typeName, const nlohmann::json & typeJSON, float x, float y, boost::uuids::uuid id = boost::uuids::random_generator()(), NodeInstance ** toFill = nullptr)
Add a node to the graph using module, type, and json.
Parameters
moduleName The name of the module that typeName is in
typeName The name of the node type in the module with the name moduleName
typeJSON The JSON to be passed to create the type
x The x location of the node
y The y location of the node
id The node ID
Return values
toFill The NodeInstance* to fill to, optional
Returns
The Result
Definition at line 94 of file GraphFunction.cpp.
References context(), insertNode(), and chi::Context::nodeTypeFromModule().
Referenced by insertNode().
localVariableFromName()
NamedDataType chi::GraphFunction::localVariableFromName (boost::string_view name) const
Get a local varaible by name.
Parameters
name The name of the variable
Returns
The local or {} if not found
Definition at line 327 of file GraphFunction.cpp.
Referenced by getOrCreateLocalVariable(), and localVariables().
localVariables()
const std::vector<NamedDataType>& chi::GraphFunction::localVariables () const inline
Get the local variables.
Returns
The local variables
Definition at line 269 of file GraphFunction.hpp.
References getOrCreateLocalVariable(), localVariableFromName(), removeLocalVariable(), renameLocalVariable(), and retypeLocalVariable().
Referenced by chi::graphFunctionToJson().
module()
GraphModule& chi::GraphFunction::module () const inline
Get the GraphModule that contains this GraphFunction.
Returns
The GraphModule.
Definition at line 320 of file GraphFunction.hpp.
Referenced by chi::compileFunction(), chi::Debugger::nodeFromFrame(), nodes(), nodesWithType(), chi::parseColonPair(), removeLocalVariable(), renameLocalVariable(), and retypeLocalVariable().
name()
std::string chi::GraphFunction::name () const inline
Get the name of the function.
Returns
The name of the function
Definition at line 317 of file GraphFunction.hpp.
Referenced by chi::compileFunction(), GraphFunction(), chi::graphFunctionToJson(), nodesWithType(), chi::parseColonPair(), and removeLocalVariable().
nodeByID()
NodeInstance * chi::GraphFunction::nodeByID (const boost::uuids::uuid & id) const
Get a node with a given ID.
Parameters
id The ID of the node
Returns
The NodeInstance, or nullptr if the ID wasn't found
Definition at line 33 of file GraphFunction.cpp.
References nodes().
Referenced by nodes().
nodes() [1/2]
std::unordered_map<boost::uuids::uuid, std::unique_ptr<NodeInstance> >& chi::GraphFunction::nodes () inline
Get the nodes in the function Usually called by connectData or connectExec or GraphFunction.
Returns
The nodes, mapped by id, value
Definition at line 55 of file GraphFunction.hpp.
Referenced by chi::graphFunctionToJson(), insertNode(), chi::jsonToGraphFunction(), nodeByID(), removeNode(), chi::validateFunctionConnectionsAreTwoWay(), and chi::validateFunctionExecOutputs().
nodes() [2/2]
const std::unordered_map<boost::uuids::uuid, std::unique_ptr<NodeInstance> >& chi::GraphFunction::nodes () const inline
Definition at line 59 of file GraphFunction.hpp.
References createEntryNodeType(), createExitNodeType(), entryNode(), functionType(), getOrInsertEntryNode(), insertNode(), module(), nodeByID(), nodesWithType(), and removeNode().
nodesWithType()
std::vector< NodeInstance * > chi::GraphFunction::nodesWithType (const boost::filesystem::path & module, boost::string_view name) const noexcept
Gets the nodes with a given type.
Parameters
module The module the type is in
name The name of the type
Returns
A vector of NodeInstance
Definition at line 81 of file GraphFunction.cpp.
References module(), and name().
Referenced by entryNode(), nodes(), removeLocalVariable(), renameExecOutput(), renameLocalVariable(), and retypeLocalVariable().
removeDataInput()
void chi::GraphFunction::removeDataInput (size_t idx)
Remove an input from the argument list Also removes invalid connections If idx is out of range, this function does nothing.
Parameters
idx The index to delete
Definition at line 206 of file GraphFunction.cpp.
Referenced by dataInputs().
removeDataOutput()
void chi::GraphFunction::removeDataOutput (size_t idx)
Remove an data output from the argument list Also removes invalid connections If idx is out of range, this function does nothing.
Parameters
idx The index to delete
Definition at line 232 of file GraphFunction.cpp.
Referenced by dataOutputs().
removeExecInput()
void chi::GraphFunction::removeExecInput (size_t idx)
Remove an exec input from the argument list If idx is out of range, this function does nothing.
Parameters
idx The index to delete
Definition at line 275 of file GraphFunction.cpp.
Referenced by execInputs().
removeExecOutput()
void chi::GraphFunction::removeExecOutput (size_t idx)
Remove an exec output from the argument list If idx is out of range, this function does nothing.
Parameters
idx The index to delete
Definition at line 295 of file GraphFunction.cpp.
Referenced by execOutputs().
removeLocalVariable()
bool chi::GraphFunction::removeLocalVariable (boost::string_view name)
Remove a local variable from the function by name.
Parameters
name The name of the local variable to remove
Returns
True if a local was actually removed, false if no local by that name existed
Definition at line 350 of file GraphFunction.cpp.
References module(), name(), nodesWithType(), and removeNode().
Referenced by localVariables().
removeNode()
Result chi::GraphFunction::removeNode (NodeInstance * nodeToRemove)
Remove a node from the function.
Also disconnect it's connections.
Parameters
nodeToRemove The node to remove
Returns
The result
Definition at line 105 of file GraphFunction.cpp.
References chi::disconnectData(), chi::disconnectExec(), chi::NodeInstance::id(), chi::NodeInstance::inputDataConnections, chi::NodeInstance::inputExecConnections, nodes(), chi::NodeInstance::outputDataConnections, and chi::NodeInstance::outputExecConnections.
Referenced by nodes(), and removeLocalVariable().
renameDataInput()
void chi::GraphFunction::renameDataInput (size_t idx, std::string newName)
Rename a data input This also updates the entry node If idx is out of range, this function does nothing.
Parameters
idx The index to rename
newName The new name
Definition at line 211 of file GraphFunction.cpp.
Referenced by dataInputs().
renameDataOutput()
void chi::GraphFunction::renameDataOutput (size_t idx, std::string newName)
Modify an data output (change it's type and docstring)
Rename a data output This also updates all exit nodes If idx is out of range, this function does nothing.
Parameters
idx The index to rename
newName The new name
Definition at line 237 of file GraphFunction.cpp.
Referenced by dataOutputs().
renameExecInput()
void chi::GraphFunction::renameExecInput (size_t idx, std::string name)
Change the name for an exec input If idx is out of range, this function does nothing.
Parameters
idx The index to change
name The new name.
Definition at line 280 of file GraphFunction.cpp.
Referenced by execInputs().
renameExecOutput()
void chi::GraphFunction::renameExecOutput (size_t idx, std::string name)
Rename an exec output If idx is out of range, this function does nothing.
Parameters
idx The index to change
name The new name.
Definition at line 300 of file GraphFunction.cpp.
References createEntryNodeType(), createExitNodeType(), and nodesWithType().
Referenced by execOutputs().
renameLocalVariable()
void chi::GraphFunction::renameLocalVariable (std::string oldName, std::string newName)
Rename a local variable.
Parameters
oldName The name of the existing local to change
newName The new name of the local
Definition at line 370 of file GraphFunction.cpp.
References module(), nodesWithType(), and chi::GraphModule::nodeTypeFromName().
Referenced by localVariables().
retypeDataInput()
void chi::GraphFunction::retypeDataInput (size_t idx, DataType newType)
Change the type of a data input This also updates the entry node and disconnects invalid connections.
If idx is out of range, this function does nothing.
Parameters
idx The index to retype
newType The new type
Definition at line 216 of file GraphFunction.cpp.
Referenced by dataInputs().
retypeDataOutput()
void chi::GraphFunction::retypeDataOutput (size_t idx, DataType newType)
Change the type of a data output This also updates all exit nodes and disconnects invalid connections.
If idx is out of range, this function does nothing.
Parameters
idx The index to retype
newType The new type
Definition at line 242 of file GraphFunction.cpp.
Referenced by dataOutputs().
retypeLocalVariable()
void chi::GraphFunction::retypeLocalVariable (boost::string_view name, DataType newType)
Set a new type to a local variable.
Parameters
name The name of the local to change
newType The new type
Definition at line 408 of file GraphFunction.cpp.
References module(), nodesWithType(), chi::GraphModule::nodeTypeFromName(), and chi::DataType::qualifiedName().
Referenced by localVariables().
setDescription()
void chi::GraphFunction::setDescription (std::string newDesc) inline
Set the description of the function.
Parameters
newDesc The new description
Definition at line 303 of file GraphFunction.hpp.
Referenced by chi::createGraphFunctionDeclarationFromJson().
The documentation for this struct was generated from the following files:
libchigraph/include/chi/GraphFunction.hpp
libchigraph/src/GraphFunction.cpp