chigraph: chig::NodeType Struct Reference
chig::NodeType Struct Reference abstract
A generic node type.
#include <chig/NodeType.hpp>
Public Member Functions
NodeType (ChigModule &mod, gsl::cstring_span<> name={}, gsl::cstring_span<> description={})
Constructor.
virtual ~NodeType ()=default
Destructor.
virtual std::unique_ptr< NodeType > clone () const =0
Clones the type.
virtual Result codegen (size_t execInputID, llvm::Module *modToCodegenInto, const llvm::DebugLoc &nodeLocation, llvm::Function *f, const gsl::span< llvm::Value *> io, llvm::BasicBlock *codegenInto, const gsl::span< llvm::BasicBlock *> outputBlocks) const =0
A virtual function that is called when this node needs to be called.
Context & context () const
Get the Context this NodeType belongs to.
gsl::span< const std::pair< DataType, std::string > > dataInputs () const
Get the data inputs for the node.
gsl::span< const std::pair< DataType, std::string > > dataOutputs () const
Get the data outputs for the node.
std::string description () const
Get the description of the NodeType.
gsl::span< const std::string > execInputs () const
Get the execution inputs for the node.
gsl::span< const std::string > execOutputs () const
Get the execution outputs for the node.
ChigModule & module () const
Get the ChigModule this NodeType belongs to.
std::string name () const
Get the name of the NodeType in the ChigModule.
bool pure ()
Get if this node is pure.
std::string qualifiedName () const
Get the qualified name of the node type, like module.name():name()
virtual nlohmann::json toJSON () const
Create the JSON necessary to store the object.
Protected Member Functions
void makePure ()
Make this node pure For more info on what this means, see https://en.wikipedia.org/wiki/Pure_function Also, UE4 implements it https://docs.unrealengine.com/latest/INT/Engine/Blueprints/UserGuide/Functions/#purevsstopimpure Pure nodes only have no inexecs and no outexecs When they are called they are backpropagated and all called They should usually be cheap and sideaffectless.
NodeInstance * nodeInstance () const
Get the node instance.
void setDataInputs (std::vector< std::pair< DataType, std::string >> newInputs)
Set the data inputs for the NodeType.
void setDataOutputs (std::vector< std::pair< DataType, std::string >> newOutputs)
Set the data outputs for the NodeType.
void setDescription (gsl::cstring_span<> newDesc)
Set the description of the node.
void setExecInputs (std::vector< std::string > newInputs)
Set the exec inputs for the NodeType.
void setExecOutputs (std::vector< std::string > newOutputs)
Set the exec outputs for the NodeType.
void setName (gsl::cstring_span<> newName)
Set the name of the type.
Detailed Description
A generic node type.
All user made types are of JsonNo deType type, which is defined in JsonModule.cpp. This allows for easy extension of the language.
Definition at line 23 of file NodeType.hpp.
Constructor & Destructor Documentation
NodeType()
chig::NodeType::NodeType (ChigModule & mod, gsl::cstring_span<> name = {}, gsl::cstring_span<> description = {}) inline
Constructor.
Parameters
mod The module to create the NodeType in
name The name of the NodeType
description The description of the NodeType
Definition at line 32 of file NodeType.hpp.
References chig::ChigModule::context(), description(), name(), and ~NodeType().
Member Function Documentation
clone()
virtual std::unique_ptr<NodeType> chig::NodeType::clone () const pure virtual
Clones the type.
Returns
The clone
Referenced by chig::NodeInstance::operator=(), and toJSON().
codegen()
virtual Result chig::NodeType::codegen (size_t execInputID, llvm::Module * modToCodegenInto, const llvm::DebugLoc & nodeLocation, llvm::Function * f, const gsl::span< llvm::Value *> io, llvm::BasicBlock * codegenInto, const gsl::span< llvm::BasicBlock *> outputBlocks) const pure virtual
A virtual function that is called when this node needs to be called.
Parameters
execInputID The ID of the exec input
modToCodegenInto The module that is being generated
nodeLocation The location of the node
f The function that is being generated
io This has the values that are the inputs and outputs of the function. This vector will always have the size of inputs.size() + outputs.size() and starts with the inputs. The types are gaurenteed to be the same as inputs and outputs
codegenInto The BasicBlock object that is used to place calls into
outputBlocks The blocks that can be outputted. This will be the same size as numOutputExecs.
Returns
The Result
Referenced by qualifiedName().
context()
Context& chig::NodeType::context () const inline
Get the Context this NodeType belongs to.
Returns
The Context
Definition at line 79 of file NodeType.hpp.
dataInputs()
gsl::span<const std::pair<DataType, std::string> > chig::NodeType::dataInputs () const inline
Get the data inputs for the node.
Returns
The data inputs in the format of {{DataType, description}, ...}
Definition at line 82 of file NodeType.hpp.
Referenced by chig::connectData(), chig::disconnectData(), and chig::NodeInstance::setType().
dataOutputs()
gsl::span<const std::pair<DataType, std::string> > chig::NodeType::dataOutputs () const inline
Get the data outputs for the node.
Returns
The data outputs in the format of {{DataType, description}, ...}
Definition at line 85 of file NodeType.hpp.
Referenced by chig::connectData(), chig::disconnectData(), and chig::NodeInstance::setType().
description()
std::string chig::NodeType::description () const inline
Get the description of the NodeType.
Returns
The description
Definition at line 73 of file NodeType.hpp.
Referenced by NodeType().
execInputs()
gsl::span<const std::string> chig::NodeType::execInputs () const inline
Get the execution inputs for the node.
Returns
The names of the inputs. The size of this vector is the size of inputs.
Definition at line 88 of file NodeType.hpp.
Referenced by chig::connectExec().
execOutputs()
gsl::span<const std::string> chig::NodeType::execOutputs () const inline
Get the execution outputs for the node.
Returns
The names of the outputs. The size is the input count.
Definition at line 91 of file NodeType.hpp.
Referenced by chig::connectExec(), and chig::disconnectExec().
module()
ChigModule& chig::NodeType::module () const inline
Get the ChigModule this NodeType belongs to.
Returns
The ChigModule
Definition at line 76 of file NodeType.hpp.
Referenced by qualifiedName().
name()
std::string chig::NodeType::name () const inline
Get the name of the NodeType in the ChigModule.
Returns
The name
Definition at line 70 of file NodeType.hpp.
Referenced by NodeType(), and qualifiedName().
nodeInstance()
NodeInstance* chig::NodeType::nodeInstance () const inline protected
Get the node instance.
Returns
the node instance
Definition at line 141 of file NodeType.hpp.
pure()
bool chig::NodeType::pure () inline
Get if this node is pure.
Returns
If it's pure
Definition at line 95 of file NodeType.hpp.
qualifiedName()
std::string chig::NodeType::qualifiedName () const inline
Get the qualified name of the node type, like module.name():name()
Returns
The qualified name
Definition at line 42 of file NodeType.hpp.
References codegen(), module(), chig::ChigModule::name(), and name().
Referenced by chig::connectData(), chig::connectExec(), chig::disconnectData(), and chig::disconnectExec().
setDataInputs()
void chig::NodeType::setDataInputs (std::vector< std::pair< DataType, std::string >> newInputs) inline protected
Set the data inputs for the NodeType.
Parameters
newInputs The new inputs
Definition at line 100 of file NodeType.hpp.
setDataOutputs()
void chig::NodeType::setDataOutputs (std::vector< std::pair< DataType, std::string >> newOutputs) inline protected
Set the data outputs for the NodeType.
Parameters
newOutputs The new outputs
Definition at line 105 of file NodeType.hpp.
setDescription()
void chig::NodeType::setDescription (gsl::cstring_span<> newDesc) inline protected
Set the description of the node.
Parameters
newDesc The new description
Definition at line 123 of file NodeType.hpp.
setExecInputs()
void chig::NodeType::setExecInputs (std::vector< std::string > newInputs) inline protected
Set the exec inputs for the NodeType.
Parameters
newInputs The new inputs
Definition at line 110 of file NodeType.hpp.
Referenced by makePure().
setExecOutputs()
void chig::NodeType::setExecOutputs (std::vector< std::string > newOutputs) inline protected
Set the exec outputs for the NodeType.
Parameters
newOutputs The new outputs
Definition at line 113 of file NodeType.hpp.
Referenced by makePure().
setName()
void chig::NodeType::setName (gsl::cstring_span<> newName) inline protected
Set the name of the type.
Parameters
newName The new name
Definition at line 119 of file NodeType.hpp.
toJSON()
virtual nlohmann::json chig::NodeType::toJSON () const inline virtual
Create the JSON necessary to store the object.
Returns
The json obejct
Definition at line 63 of file NodeType.hpp.
References clone().
Referenced by chig::connectData(), and chig::disconnectData().
The documentation for this struct was generated from the following file:
include/chig/NodeType.hpp