chigraph: chi::Context Struct Reference
chi::Context Struct Reference
The class that handles the loading, creation, storing, and compilation of modules It also stores a LLVMContext object to be used everywhere.
#include <chi/Context.hpp>
Public Member Functions
Context (const boost::filesystem::path &workPath={})
Creates a context with just the lang module.
Context (const Context &context)=delete
Context (Context &&)=delete
~Context ()
Destructor.
bool addModule (std::unique_ptr< ChiModule > modToAdd) noexcept
Adds a custom module to the Context.
Result addModuleFromJson (const boost::filesystem::path &fullName, const nlohmann::json &json, GraphModule **toFill=nullptr)
Load a module from JSON – avoid this use the string overload.
Result compileModule (const boost::filesystem::path &fullName, bool linkDependencies, std::unique_ptr< llvm::Module > *toFill)
Compile a module to a llvm::Module.
Result compileModule (ChiModule &mod, bool linkDepdnencies, std::unique_ptr< llvm::Module > *toFill)
Compile a module to a llvm::Module.
Result fetchModule (const boost::filesystem::path &name, bool recursive)
Downloads a module from a remote URL, currently supports.
std::vector< NodeInstance * > findInstancesOfType (const boost::filesystem::path &module, boost::string_view typeName) const
Find all uses of a node type in all the loaded modules.
bool hasWorkspace () const noexcept
Check if this context has a workspace bound to it – same as !workspacePath().empty()
LangModule * langModule () const
Get the LangModule, if it has been loaded.
std::vector< std::string > listModulesInWorkspace () const noexcept
Get the list of modules in the workspace.
llvm::LLVMContext & llvmContext ()
Get the LLVMContext
Result loadModule (const boost::filesystem::path &name, Flags< LoadSettings > flags=LoadSettings::Default, ChiModule **toFill=nullptr)
Load a module from disk, also loads dependencies !name.empty()
ChiModule * moduleByFullName (const boost::filesystem::path &fullModuleName) const noexcept
Gets the module by the full name.
const ModuleCache & moduleCache () const
Get the module cache.
ModuleCache & moduleCache ()
Get the module cache.
std::vector< ChiModule * > modules () const
Get the modules in the Context.
GraphModule * newGraphModule (const boost::filesystem::path &fullName)
Create a new GraphModule with the given full name.
Result nodeTypeFromModule (const boost::filesystem::path &moduleName, boost::string_view typeName, const nlohmann::json &data, std::unique_ptr< NodeType > *toFill) noexcept
Gets a NodeType from the JSON and name.
Result typeFromModule (const boost::filesystem::path &module, boost::string_view name, DataType *toFill) noexcept
Gets a DataType from a module.
bool unloadModule (const boost::filesystem::path &fullName)
Unloads a module.
boost::filesystem::path workspacePath () const
Get the workspace path of the Context.
Detailed Description
The class that handles the loading, creation, storing, and compilation of modules It also stores a LLVMContext object to be used everywhere.
It stores all the modules and allows for compilation of them. Basic use looks like this:
chi::Context ctx{"/path/to/workspace"};
chi::Reuslt res = ctx.loadModule("github.com/russelltg/hellochigraph");
if (!res) {
    std::cerr << res << std::endl;
    return;
}
Definition at line 49 of file Context.hpp.
Constructor & Destructor Documentation
Context()
chi::Context::Context (const boost::filesystem::path & workPath = {})
Creates a context with just the lang module.
Parameters
workPath Path to the workspace, or a subdirectory of the workspace
Member Function Documentation
addModule()
bool chi::Context::addModule (std::unique_ptr< ChiModule > modToAdd) noexcept
Adds a custom module to the Context.
Parameters
modToAdd The module to add. The context will take excluseive ownership of it.
Returns
True if the module was added (it didn't exist before)
Definition at line 458 of file Context.cpp.
addModuleFromJson()
Result chi::Context::addModuleFromJson (const boost::filesystem::path & fullName, const nlohmann::json & json, GraphModule ** toFill = nullptr)
Load a module from JSON – avoid this use the string overload.
Parameters
[in] fullName The full path of the module, including URL
[in] json The JSON data
[out] toFill The GraphModule* to fill into, optional
Returns
The Result
Definition at line 429 of file Context.cpp.
References chi::Result::addScopedContext(), chi::ChiModule::fullName(), and chi::jsonToGraphModule().
compileModule() [1/2]
Result chi::Context::compileModule (const boost::filesystem::path & fullName, bool linkDependencies, std::unique_ptr< llvm::Module > * toFill)
Compile a module to a llvm::Module.
Parameters
[in] fullName The full name of the module to compile. If moduleByFullName(fullName) == nullptr, this function has no side-effects
[in] linkDependencies Should all the dependencies be linked in? If this is true this module will be ready to be run.
[out] toFill The llvm::Module to fill – this can be nullptr it will be replaced
Precondition
toFill isn't null (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The Result
Referenced by hasWorkspace(), nodeTypeFromModule(), and chi::Debugger::start().
compileModule() [2/2]
Result chi::Context::compileModule (ChiModule & mod, bool linkDepdnencies, std::unique_ptr< llvm::Module > * toFill)
Compile a module to a llvm::Module.
Parameters
[in] mod The module to compile
[in] linkDepdnencies Should the dependencies be linked into the module?
[out] toFill The llvm::Module to fill – this can be nullptr it will be replaced
Precondition
toFill != nullptr (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The Result
Definition at line 536 of file Context.cpp.
References chi::Result::addEntry(), chi::Result::addScopedContext(), chi::ChiModule::dependencies(), chi::ChiModule::fullName(), chi::ChiModule::fullNamePath(), chi::ChiModule::generateModule(), and chi::ChiModule::lastEditTime().
fetchModule()
Result chi::Context::fetchModule (const boost::filesystem::path & name, bool recursive)
Downloads a module from a remote URL, currently supports.
github
Precondition
hasWorkspace() == true
Parameters
name The name of the module to fetch
recursive Should all dependencies be cloned as well?
Returns
The Result
Definition at line 153 of file Context.cpp.
References chi::Result::addScopedContext(), and chi::resolveUrlFromModuleName().
findInstancesOfType()
std::vector< NodeInstance * > chi::Context::findInstancesOfType (const boost::filesystem::path & module, boost::string_view typeName) const
Find all uses of a node type in all the loaded modules.
Parameters
module The name of the module that the type being search for is in
typeName The name of the type in module to search for.
Definition at line 652 of file Context.cpp.
References chi::workspaceFromChildPath().
Referenced by hasWorkspace(), chi::GraphModule::removeFunction(), and chi::GraphFunction::setName().
hasWorkspace()
bool chi::Context::hasWorkspace () const inline noexcept
Check if this context has a workspace bound to it – same as !workspacePath().empty()
Returns
If it has a workspace
Definition at line 137 of file Context.hpp.
References compileModule(), findInstancesOfType(), and workspacePath().
langModule()
LangModule* chi::Context::langModule () const inline
Get the LangModule, if it has been loaded.
Returns
The LangModule
Definition at line 171 of file Context.hpp.
listModulesInWorkspace()
std::vector< std::string > chi::Context::listModulesInWorkspace () const noexcept
Get the list of modules in the workspace.
Returns
The module list
Definition at line 70 of file Context.cpp.
llvmContext()
llvm::LLVMContext& chi::Context::llvmContext () inline
Get the LLVMContext
Returns
The LLVMContext
Definition at line 167 of file Context.hpp.
Referenced by chi::GraphStruct::dataType(), chi::GraphModule::generateModule(), chi::LangModule::LangModule(), chi::ModuleCache::retrieveFromCache(), and chi::LangModule::typeFromName().
loadModule()
Result chi::Context::loadModule (const boost::filesystem::path & name, Flags< LoadSettings > flags = LoadSettings::Default, ChiModule ** toFill = nullptr)
Load a module from disk, also loads dependencies !name.empty()
Parameters
[in] name The name of the moudle
[out] toFill The module that was loaded, optional
Returns
The result
Definition at line 93 of file Context.cpp.
References chi::Result::addScopedContext(), chi::Fetch, chi::FetchRecursive, and chi::ChiModule::updateLastEditTime().
Referenced by chi::ChiModule::addDependency().
moduleByFullName()
ChiModule * chi::Context::moduleByFullName (const boost::filesystem::path & fullModuleName) const noexcept
Gets the module by the full name.
Parameters
fullModuleName The name of the module to find
Returns
ret_module The module that has the full name fullModuleName, nullptr if none were found
Definition at line 50 of file Context.cpp.
Referenced by chi::Debugger::nodeFromFrame().
moduleCache() [1/2]
const ModuleCache& chi::Context::moduleCache () const inline
Get the module cache.
Returns
The ModuleCache
Definition at line 185 of file Context.hpp.
moduleCache() [2/2]
ModuleCache& chi::Context::moduleCache () inline
Get the module cache.
Returns
The ModuleCache
Definition at line 188 of file Context.hpp.
References chi::Default, chi::interpretLLVMIR(), chi::interpretLLVMIRAsMain(), chi::stringifyLLVMType(), and chi::workspaceFromChildPath().
modules()
std::vector<ChiModule*> chi::Context::modules () const inline
Get the modules in the Context.
Returns
The modules
Definition at line 175 of file Context.hpp.
newGraphModule()
GraphModule * chi::Context::newGraphModule (const boost::filesystem::path & fullName)
Create a new GraphModule with the given full name.
Parameters
fullName The new name
Returns
The created GraphModule
Definition at line 57 of file Context.cpp.
References chi::ChiModule::fullName().
Referenced by chi::jsonToGraphModule().
nodeTypeFromModule()
Result chi::Context::nodeTypeFromModule (const boost::filesystem::path & moduleName, boost::string_view typeName, const nlohmann::json & data, std::unique_ptr< NodeType > * toFill) noexcept
Gets a NodeType from the JSON and name.
Parameters
[in] moduleName The full module name.
[in] typeName The name of the node type
[in] data The JSON data that is used to construct the NodeType.
[out] toFill The point to fill
Precondition
toFill != nullptr (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The Result
Definition at line 508 of file Context.cpp.
References chi::Result::addEntry(), compileModule(), and chi::ChiModule::fullName().
Referenced by chi::GraphFunction::createEntryNodeType(), chi::GraphFunction::createExitNodeType(), chi::GraphFunction::insertNode(), chi::jsonToGraphFunction(), and chi::GraphFunction::setName().
typeFromModule()
Result chi::Context::typeFromModule (const boost::filesystem::path & module, boost::string_view name, DataType * toFill) noexcept
Gets a DataType from a module.
Parameters
[in] module The full name of the module
[in] name The name of the type, required
[out] toFill The type to fill
Precondition
toFill != nullptr
Returns
The result
Definition at line 487 of file Context.cpp.
References chi::Result::addEntry(), and chi::ChiModule::typeFromName().
Referenced by chi::compileFunction(), chi::createGraphFunctionDeclarationFromJson(), chi::GraphModule::createNodeTypeFromCCode(), chi::jsonToGraphFunction(), chi::jsonToGraphStruct(), chi::LangModule::LangModule(), and chi::GraphModule::nodeTypeFromName().
unloadModule()
bool chi::Context::unloadModule (const boost::filesystem::path & fullName)
Unloads a module.
Parameters
fullName The full name of the module to unload
Returns
True if a module was unloaded
Definition at line 474 of file Context.cpp.
References chi::ChiModule::fullName().
workspacePath()
boost::filesystem::path chi::Context::workspacePath () const inline
Get the workspace path of the Context.
Returns
The workspace path
Definition at line 134 of file Context.hpp.
Referenced by chi::ModuleCache::cachePathForModule(), hasWorkspace(), chi::jsonToGraphModule(), and chi::GraphModule::sourceFilePath().
The documentation for this struct was generated from the following files:
libchigraph/include/chi/Context.hpp
libchigraph/src/Context.cpp