chigraph: chig::Context Struct Reference
chig::Context Struct Reference
The class that handles the loading, creation, storing, and compilation of modules It also stores a LLVMContext object to be used everywhere.
#include <chig/Context.hpp>
Public Member Functions
Context (const boost::filesystem::path &workPath={})
Creates a context with just the lang module.
Context (const Context &context)=delete
Context (Context &&)=delete
bool addModule (std::unique_ptr< ChigModule > modToAdd) noexcept
Adds a custom module to the Context This usually doesn't get called, use the gsl::string_span<> overload instead.
Result addModuleFromJson (const boost::filesystem::path &fullName, const nlohmann::json &json, GraphModule **toFill=nullptr)
Load a module from JSON – avoid this use the string overload.
CModule * cModule () const
Get the CModule, if it has been loaded.
Result compileModule (const boost::filesystem::path &fullName, std::unique_ptr< llvm::Module > *toFill)
Compile a module to a llvm::Module.
Result compileModule (ChigModule &mod, std::unique_ptr< llvm::Module > *toFill)
Compile a module to a llvm::Module.
bool hasWorkspace () const noexcept
Check if this context has a workspace bound to it – same as !workspacePath().empty()
LangModule * langModule () const
Get the LangModule, if it has been loaded.
std::vector< std::string > listModulesInWorkspace () const noexcept
Get the list of modules in the workspace.
llvm::LLVMContext & llvmContext () const
Get the LLVMContext
Result loadModule (const boost::filesystem::path &name, ChigModule **toFill=nullptr)
Load a module from disk.
ChigModule * moduleByFullName (const boost::filesystem::path &fullModuleName) const noexcept
Gets the module by the full name.
GraphModule * newGraphModule (const boost::filesystem::path &fullName)
Create a new GraphModule with the given full name.
Result nodeTypeFromModule (const boost::filesystem::path &moduleName, gsl::cstring_span<> typeName, const nlohmann::json &data, std::unique_ptr< NodeType > *toFill) noexcept
Gets a NodeType from the JSON and name.
size_t numModules () const
Get the number of modules this Context has.
Result typeFromModule (const boost::filesystem::path &module, gsl::cstring_span<> name, DataType *toFill) noexcept
Gets a DataType from a module.
bool unloadModule (const boost::filesystem::path &fullName)
Unloads a module.
boost::filesystem::path workspacePath () const
Get the workspace path of the Context.
Detailed Description
The class that handles the loading, creation, storing, and compilation of modules It also stores a LLVMContext object to be used everywhere.
Definition at line 30 of file Context.hpp.
Constructor & Destructor Documentation
Context()
chig::Context::Context (const boost::filesystem::path & workPath = {})
Creates a context with just the lang module.
Parameters
workPath Path to the workspace, or a subdirectory of the workspace
Member Function Documentation
addModule()
bool chig::Context::addModule (std::unique_ptr< ChigModule > modToAdd) noexcept
Adds a custom module to the Context This usually doesn't get called, use the gsl::string_span<> overload instead.
Parameters
modToAdd The module to add. The context will take excluseive ownership of it.
Returns
True if the module was added (it didn't exist before)
Definition at line 158 of file Context.cpp.
References moduleByFullName().
Referenced by loadModule(), and newGraphModule().
addModuleFromJson()
Result chig::Context::addModuleFromJson (const boost::filesystem::path & fullName, const nlohmann::json & json, GraphModule ** toFill = nullptr)
Load a module from JSON – avoid this use the string overload.
Parameters
[in] fullName The full path of the module, including URL
[in] json The JSON data
[out] toFill The GraphModule* to fill into, optional
Returns
The Result
Definition at line 131 of file Context.cpp.
References chig::ChigModule::fullName(), chig::jsonToGraphModule(), moduleByFullName(), and unloadModule().
Referenced by loadModule().
cModule()
CModule* chig::Context::cModule () const inline
Get the CModule, if it has been loaded.
Returns
The CModule
Definition at line 138 of file Context.hpp.
References chig::interpretLLVMIR(), chig::interpretLLVMIRAsMain(), chig::stringifyLLVMType(), and chig::workspaceFromChildPath().
compileModule() [1/2]
Result chig::Context::compileModule (const boost::filesystem::path & fullName, std::unique_ptr< llvm::Module > * toFill)
Compile a module to a llvm::Module.
Parameters
[in] fullName The full name of the module to compile. If moduleByFullName(fullName) == nullptr, this function has no side-effects
[out] toFill The llvm::Module to fill – this can be nullptr it will be replaced
Precondition
toFill isn't null (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The Result
Definition at line 228 of file Context.cpp.
References chig::Result::addEntry(), and moduleByFullName().
Referenced by compileModule(), hasWorkspace(), and chig::Debugger::start().
compileModule() [2/2]
Result chig::Context::compileModule (ChigModule & mod, std::unique_ptr< llvm::Module > * toFill)
Compile a module to a llvm::Module.
Parameters
[in] mod The module to compile
[out] toFill The llvm::Module to fill – this can be nullptr it will be replaced
Precondition
toFill != nullptr (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The Result
Definition at line 241 of file Context.cpp.
References chig::Result::addEntry(), compileModule(), chig::ChigModule::dependencies(), chig::ChigModule::fullName(), chig::ChigModule::generateModule(), llvmContext(), and chig::workspaceFromChildPath().
hasWorkspace()
bool chig::Context::hasWorkspace () const inline noexcept
Check if this context has a workspace bound to it – same as !workspacePath().empty()
Returns
If it has a workspace
Definition at line 105 of file Context.hpp.
References compileModule(), and workspacePath().
langModule()
LangModule* chig::Context::langModule () const inline
Get the LangModule, if it has been loaded.
Returns
The LangModule
Definition at line 134 of file Context.hpp.
listModulesInWorkspace()
std::vector< std::string > chig::Context::listModulesInWorkspace () const noexcept
Get the list of modules in the workspace.
Returns
The module list
Definition at line 56 of file Context.cpp.
References workspacePath().
llvmContext()
llvm::LLVMContext& chig::Context::llvmContext () const inline
Get the LLVMContext
Returns
The LLVMContext
Definition at line 130 of file Context.hpp.
Referenced by compileModule().
loadModule()
chig::Result chig::Context::loadModule (const boost::filesystem::path & name, ChigModule ** toFill = nullptr)
Load a module from disk.
Parameters
[in] name The name of the moudle
[out] toFill The module that was loaded, optional
Returns
The result
Definition at line 79 of file Context.cpp.
References chig::Result::addEntry(), addModule(), addModuleFromJson(), and workspacePath().
Referenced by chig::ChigModule::addDependency().
moduleByFullName()
ChigModule * chig::Context::moduleByFullName (const boost::filesystem::path & fullModuleName) const noexcept
Gets the module by the full name.
Parameters
fullModuleName The name of the module to find
Returns
ret_module The module that has the full name fullModuleName, nullptr if none were found
Definition at line 34 of file Context.cpp.
Referenced by addModule(), addModuleFromJson(), compileModule(), nodeTypeFromModule(), and typeFromModule().
newGraphModule()
GraphModule * chig::Context::newGraphModule (const boost::filesystem::path & fullName)
Create a new GraphModule with the given full name.
Parameters
fullName The new name
Returns
The created GraphModule
Definition at line 43 of file Context.cpp.
References addModule().
Referenced by chig::jsonToGraphModule().
nodeTypeFromModule()
Result chig::Context::nodeTypeFromModule (const boost::filesystem::path & moduleName, gsl::cstring_span<> typeName, const nlohmann::json & data, std::unique_ptr< NodeType > * toFill) noexcept
Gets a NodeType from the JSON and name.
Parameters
[in] moduleName The full module name.
[in] typeName The name of the node type
[in] data The JSON data that is used to construct the NodeType.
[out] toFill The point to fill
Precondition
toFill != nullptr (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The Result
Definition at line 212 of file Context.cpp.
References chig::Result::addEntry(), and moduleByFullName().
Referenced by chig::GraphFunction::createEntryNodeType(), chig::GraphFunction::createExitNodeType(), chig::GraphFunction::insertNode(), and chig::jsonToGraphFunction().
numModules()
size_t chig::Context::numModules () const inline
Get the number of modules this Context has.
Returns
The module count
Definition at line 127 of file Context.hpp.
typeFromModule()
Result chig::Context::typeFromModule (const boost::filesystem::path & module, gsl::cstring_span<> name, DataType * toFill) noexcept
Gets a DataType from a module.
Parameters
[in] module The full name of the module
[in] name The name of the type, required
[out] toFill The type to fill
Precondition
toFill != nullptr
Returns
The result
Definition at line 191 of file Context.cpp.
References chig::Result::addEntry(), moduleByFullName(), and chig::ChigModule::typeFromName().
Referenced by chig::compileFunction(), chig::createGraphFunctionDeclarationFromJson(), chig::jsonToGraphFunction(), chig::jsonToGraphStruct(), chig::LangModule::LangModule(), chig::CModule::nodeTypeFromName(), and chig::GraphModule::nodeTypeFromName().
unloadModule()
bool chig::Context::unloadModule (const boost::filesystem::path & fullName)
Unloads a module.
Parameters
fullName The full name of the module to unload
Returns
True if a module was unloaded
Definition at line 178 of file Context.cpp.
Referenced by addModuleFromJson().
workspacePath()
boost::filesystem::path chig::Context::workspacePath () const inline
Get the workspace path of the Context.
Returns
The workspace path
Definition at line 102 of file Context.hpp.
Referenced by hasWorkspace(), listModulesInWorkspace(), loadModule(), and chig::GraphModule::sourceFilePath().
The documentation for this struct was generated from the following files:
libchig/include/chig/Context.hpp
libchig/src/Context.cpp