chigraph: chig::GraphStruct Struct Reference
chig::GraphStruct Struct Reference
A class holding a compound type defined in a GraphModule.
#include <chig/GraphStruct.hpp>
Public Member Functions
GraphStruct (GraphModule &mod, std::string name)
GraphType constructor; don't use this use GraphModule::newStruct.
void addType (DataType ty, std::string name, size_t addBefore)
Add a new type to the struct.
Context & context () const
Get the context.
DataType dataType ()
Get the DataType of the struct.
void modifyType (size_t id, DataType newTy, std::string newName)
Change the type and name of a type.
GraphModule & module () const
Get the module.
const std::string & name () const
Get the name of the type.
void removeType (size_t id)
Remove a type from a struct.
const std::vector< NamedDataType > & types () const
Get the types the struct contains.
Detailed Description
A class holding a compound type defined in a GraphModule.
Definition at line 15 of file GraphStruct.hpp.
Constructor & Destructor Documentation
GraphStruct()
chig::GraphStruct::GraphStruct (GraphModule & mod, std::string name)
GraphType constructor; don't use this use GraphModule::newStruct.
Parameters
mod Module to add to
name name of the type
Definition at line 11 of file GraphStruct.cpp.
References name().
Member Function Documentation
addType()
void chig::GraphStruct::addType (DataType ty, std::string name, size_t addBefore)
Add a new type to the struct.
Parameters
ty The type
name The name of the type
addBefore The type to add the new type before. Use types().size() to add to the end
Definition at line 14 of file GraphStruct.cpp.
References types(), and chig::DataType::valid().
Referenced by types().
context()
Context& chig::GraphStruct::context () const inline
Get the context.
Returns
The Context
Definition at line 23 of file GraphStruct.hpp.
Referenced by dataType().
modifyType()
void chig::GraphStruct::modifyType (size_t id, DataType newTy, std::string newName)
Change the type and name of a type.
Parameters
id The ID to change
newTy The new type
newName The new name
Definition at line 23 of file GraphStruct.cpp.
References types(), and chig::DataType::valid().
Referenced by types().
module()
GraphModule& chig::GraphStruct::module () const inline
Get the module.
Returns
The GraphModule
Definition at line 27 of file GraphStruct.hpp.
Referenced by dataType(), and chig::GraphModule::removeStruct().
name()
const std::string& chig::GraphStruct::name () const inline
Get the name of the type.
Returns
the name
Definition at line 31 of file GraphStruct.hpp.
Referenced by dataType(), and GraphStruct().
removeType()
void chig::GraphStruct::removeType (size_t id)
Remove a type from a struct.
Parameters
id The ID to remove
Definition at line 32 of file GraphStruct.cpp.
References types().
Referenced by types().
types()
const std::vector<NamedDataType>& chig::GraphStruct::types () const inline
Get the types the struct contains.
Returns
The types
Definition at line 35 of file GraphStruct.hpp.
References addType(), dataType(), modifyType(), and removeType().
Referenced by addType(), dataType(), chig::graphStructToJson(), modifyType(), and removeType().
The documentation for this struct was generated from the following files:
libchig/include/chig/GraphStruct.hpp
libchig/src/GraphStruct.cpp