chigraph: chi::CModule Struct Reference
chi::CModule Struct Reference
The CModule is the module that supplies functionality to create C bindings.
#include <chi/CModule.hpp>
Public Member Functions
CModule (Context &ctx)
Contstructor–construct with a context. This is usually called by Context.
~CModule ()=default
Destructor.
Result addDependency (const boost::filesystem::path &newDepFullPath)
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Context & context () const
Get the Context that this module belongs to.
Result createNodeTypeFromCCode (const std::string &code, const std::string &functionName, const std::vector< std::string > &clangArgs, std::unique_ptr< NodeType > *toFill)
const std::unordered_set< boost::filesystem::path > & dependencies () const
Get the dependencies.
const std::vector< std::string > & extraArguments () const
Get the extra arguments.
std::string fullName () const
Get the full name of the module.
boost::filesystem::path fullNamePath () const
Get the full name of the module in a path.
Result generateModule (llvm::Module &) override
Generate a llvm::Module from the module.
Result nodeTypeFromName (boost::string_view typeName, const nlohmann::json &jsonData, std::unique_ptr< NodeType > *toFill) override
Create a node type that is in the module from the name and json.
std::vector< std::string > nodeTypeNames () const override
Get the possible node type names.
bool removeDependency (std::string depName)
Remove a dependency Does not unload from context.
void setExtraArguments (std::vector< std::string > extraArgs)
Set extra arguments to pass to clang for generating C code.
std::string shortName () const
Get the short name of the module (the last bit)
DataType typeFromName (boost::string_view name) override
Get a DataType from the name.
std::vector< std::string > typeNames () const override
Get the possible DataType names.
Detailed Description
The CModule is the module that supplies functionality to create C bindings.
Definition at line 22 of file CModule.hpp.
Member Function Documentation
addDependency()
Result chi::ChiModule::addDependency (const boost::filesystem::path & newDepFullPath) inherited
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Parameters
newDepFullPath The dependency, full path
Returns
The result
Definition at line 13 of file ChiModule.cpp.
References chi::ChiModule::context(), and chi::Context::loadModule().
Referenced by chi::ChiModule::dependencies(), and chi::GraphModule::GraphModule().
context()
Context& chi::ChiModule::context () const inline inherited
Get the Context that this module belongs to.
Returns
The context
Definition at line 65 of file ChiModule.hpp.
References chi::ChiModule::generateModule().
Referenced by chi::ChiModule::addDependency(), chi::createGraphFunctionDeclarationFromJson(), chi::jsonToGraphStruct(), chi::LangModule::LangModule(), chi::Debugger::nodeFromFrame(), chi::NodeType::NodeType(), nodeTypeFromName(), chi::GraphModule::nodeTypeFromName(), chi::GraphModule::saveToDisk(), chi::GraphModule::sourceFilePath(), chi::Debugger::start(), and chi::LangModule::typeFromName().
dependencies()
const std::unordered_set<boost::filesystem::path>& chi::ChiModule::dependencies () const inline inherited
Get the dependencies.
Returns
The dependencies
Definition at line 73 of file ChiModule.hpp.
References chi::ChiModule::addDependency().
Referenced by chi::Context::compileModule(), and chi::graphModuleToJson().
extraArguments()
const std::vector<std::string>& chi::CModule::extraArguments () const inline
Get the extra arguments.
Returns
The extra arguments
Definition at line 44 of file CModule.hpp.
generateModule()
Result chi::CModule::generateModule (llvm::Module & module) inline override virtual
Generate a llvm::Module from the module.
Usually called by Context::compileModule
Parameters
module The llvm::Module to fill into – must be already filled with dependencies
Returns
The result
Implements chi::ChiModule.
Definition at line 34 of file CModule.hpp.
nodeTypeFromName()
Result chi::CModule::nodeTypeFromName (boost::string_view name, const nlohmann::json & jsonData, std::unique_ptr< NodeType > * toFill) override virtual
Create a node type that is in the module from the name and json.
Parameters
name The name of the node type to create
jsonData The extra JSON data for the node
Return values
toFill The NodeType object to fill
Precondition
toFill isn't null (the value the unique_ptr points to be can be null, but not the pointer to the unique_ptr)
Returns
The result
Implements chi::ChiModule.
Definition at line 189 of file CModule.cpp.
References chi::Result::addEntry(), chi::ChiModule::context(), chi::ChiModule::fullName(), chi::parseColonPair(), chi::parseObjectPair(), chi::stringifyLLVMType(), and chi::Context::typeFromModule().
nodeTypeNames()
std::vector<std::string> chi::CModule::nodeTypeNames () const inline override virtual
Get the possible node type names.
Returns
A std::vector of the possible names
Implements chi::ChiModule.
Definition at line 32 of file CModule.hpp.
removeDependency()
bool chi::ChiModule::removeDependency (std::string depName) inline inherited
Remove a dependency Does not unload from context.
Parameters
depName The name of the dependency to remove
Returns
If one was removed
Definition at line 86 of file ChiModule.hpp.
setExtraArguments()
void chi::CModule::setExtraArguments (std::vector< std::string > extraArgs) inline
Set extra arguments to pass to clang for generating C code.
Parameters
extraArgs The new extra arguments
Definition at line 38 of file CModule.hpp.
shortName()
std::string chi::ChiModule::shortName () const inline inherited
Get the short name of the module (the last bit)
Returns
The name
Definition at line 58 of file ChiModule.hpp.
typeFromName()
DataType chi::CModule::typeFromName (boost::string_view name) override virtual
Get a DataType from the name.
Parameters
name The name of the type
Returns
The data type, or an invalid DataType if failed
Implements chi::ChiModule.
Definition at line 183 of file CModule.cpp.
The documentation for this struct was generated from the following files:
libchigraph/include/chi/CModule.hpp
libchigraph/src/CModule.cpp