chigraph: chi::Result Struct Reference
chi::Result Struct Reference
The result object, used for identifiying errors with good diagnostics.
#include <chi/Result.hpp>
Classes
struct ScopedContext
A helper object for contexts that should be removed at the end of a scope.
Public Member Functions
Result ()
Default constructor; defaults to success.
int addContext (const nlohmann::json &data)
Add some json that will ALWAYS be merged with entries that are added and when results are added to this Result.
void addEntry (const char *ec, const char *overview, nlohmann::json data)
Add a entry to the result, either a warning or an error.
ScopedContext addScopedContext (const nlohmann::json &data)
Add a context with a scope Example usage:
chi::Result res;
res.contextJson(); // returns {}
{
    auto scopedCtx = res.addScopedContext({{"Module", "lang"}});
    res.contextJson(); // returns {"module": "lang"}
}
res.contextJson(); // returns {}
.
nlohmann::json contextJson () const
Get the JSON associated with the context that's been added.
std::string dump () const
Dump to a pretty-printed error message.
operator bool () const
Success test.
bool operator! () const
!Success test
void removeContext (int id)
Removes a previously added context.
bool success () const
Success test.
Public Attributes
bool mSuccess = true
If it's successful.
nlohmann::json result_json
The result JSON.
Related Functions
(Note that these are not member functions.)
Result operators
Result operator+ (const Result &lhs, const Result &rhs)
Append two Result objects.
Result & operator+= (Result &lhs, const Result &rhs)
Append one result to an existing one.
std::ostream & operator<< (std::ostream &lhs, const Result &rhs)
Stream operator.
Detailed Description
The result object, used for identifiying errors with good diagnostics.
Usage:
If you want to construct a default result object, just call the default constructor:
Result res;
res is the most common name for an error object, prefer it to other names.
When an error, warning, or just some event that requries logging needs to be added to the result object, call Result::addEntry:
Result res;
res.addEntry("E231", "Some error occured", {{"Line Number", 34}});
Note the E at the beginning of the error code, this is important. If it's an E, it's considered an error, and will mark the result as errored. If it's a W, then it's logged, but it's still considred successful.
If you're calling another operation that emits a Result object, then there's an easy to integrate that result object: the opeartor+=
Result res;
res += connectExec(...); // or any function that returns a Result
Standardized names in data:
In order to have good parsing of errors, some standards are good. If you are trying to represent this data in your error, use these standards so it can be parsed later on and presented to the user in a nice way
Name in JSON Description
Node ID The ID of the node that errored
What is EUKN?
Not every error in chigraph is documented and tested. Errors with numbers are tested and possibly documented. EUKN errors are just undocumented errors.
Implementation Details:
Result objects store a json object that represents the error metadata. It's an array, each being an object containing three objects:
errorcode: The errorcode. This is an identifier representng the error: a character followed by a number. The value of the character changes the behaviour:
E: it's an error and sets success to false.
W: it's a warning
I: it's just info
If it's anything else, that it will cause an assertion
overview: A simple string representing the generics of the problem. It shouldn't differ from error to error, if you need to include specifics use the data element
data: Extra metadata for the error, including context and how the error occured.
Examples:
SubprocessExample.cpp.
Definition at line 70 of file Result.hpp.
Member Function Documentation
addContext()
int chi::Result::addContext (const nlohmann::json & data)
Add some json that will ALWAYS be merged with entries that are added and when results are added to this Result.
Parameters
data The json to merge with every entry
Returns
The ID for this context, use this value with removeContext to remove it
Definition at line 80 of file Result.cpp.
Referenced by addScopedContext(), and Result().
addEntry()
void chi::Result::addEntry (const char * ec, const char * overview, nlohmann::json data)
Add a entry to the result, either a warning or an error.
Parameters
ec The error/warning code. If it starts with E, then it is an error and success is set to false, if it starts with a W it's a warning and success can stay true if it is still true.
overview Basic overview of the error, this shouldn't change based on the instance of the error
data The detailed description this instance of the error.
Precondition
data.is_object() == true
Definition at line 50 of file Result.cpp.
References contextJson(), mSuccess, and result_json.
Referenced by chi::Subprocess::closeStdIn(), chi::compileFunction(), chi::Context::compileModule(), chi::connectData(), chi::connectExec(), chi::createGraphFunctionDeclarationFromJson(), chi::GraphModule::createNodeTypeFromCCode(), chi::disconnectData(), chi::disconnectExec(), chi::GraphFunction::insertNode(), chi::interpretLLVMIR(), chi::interpretLLVMIRAsMain(), chi::jsonToGraphFunction(), chi::jsonToGraphModule(), chi::jsonToGraphStruct(), chi::Context::nodeTypeFromModule(), chi::LangModule::nodeTypeFromName(), chi::GraphModule::nodeTypeFromName(), chi::Debugger::pause(), chi::Debugger::processContinue(), chi::Subprocess::pushToStdIn(), Result(), chi::GraphModule::saveToDisk(), chi::Debugger::setBreakpoint(), chi::Debugger::start(), chi::Subprocess::start(), chi::Debugger::terminate(), chi::Context::typeFromModule(), chi::validateFunctionConnectionsAreTwoWay(), and chi::validateFunctionExecOutputs().
addScopedContext()
ScopedContext chi::Result::addScopedContext (const nlohmann::json & data) inline
Add a context with a scope Example usage:
chi::Result res;
res.contextJson(); // returns {}
{
    auto scopedCtx = res.addScopedContext({{"Module", "lang"}});
    res.contextJson(); // returns {"module": "lang"}
}
res.contextJson(); // returns {}
.
Parameters
data The data to add to each entry
Returns
The ScopedContext object. Shouldn't be discarded.
Definition at line 120 of file Result.hpp.
References addContext(), contextJson(), and removeContext().
Referenced by chi::Context::addModuleFromJson(), chi::Context::compileModule(), chi::Context::fetchModule(), chi::jsonToGraphModule(), chi::Context::loadModule(), chi::validateFunctionConnectionsAreTwoWay(), chi::validateFunctionExecOutputs(), and chi::validateFunctionNodeInputs().
contextJson()
nlohmann::json chi::Result::contextJson () const
Get the JSON associated with the context that's been added.
Returns
The context JSON
Definition at line 89 of file Result.cpp.
Referenced by addEntry(), addScopedContext(), operator+(), and operator+=().
dump()
std::string chi::Result::dump () const
Dump to a pretty-printed error message.
Returns
The human-readable error message
Definition at line 61 of file Result.cpp.
References result_json.
Referenced by operator!(), and operator<<().
operator bool()
chi::Result::operator bool () const inline explicit
Success test.
Returns
True if successful
Definition at line 134 of file Result.hpp.
References success().
operator!()
bool chi::Result::operator! () const inline
!Success test
Returns
If it's not successful
Definition at line 142 of file Result.hpp.
References dump(), and success().
removeContext()
void chi::Result::removeContext (int id)
Removes a previously added context.
Parameters
id The ID for the context added with addContext
Definition at line 87 of file Result.cpp.
Referenced by addScopedContext(), and chi::Result::ScopedContext::~ScopedContext().
success()
bool chi::Result::success () const inline
Success test.
Returns
If it's successful
Definition at line 138 of file Result.hpp.
References mSuccess.
Referenced by operator bool(), operator!(), operator+(), and operator+=().
Friends And Related Function Documentation
operator+()
Result operator+ (const Result & lhs, const Result & rhs) related
Append two Result objects.
Both of the contexts are merged. The entires in lhs have the rhs context applied to them, and viceversa as well
Parameters
lhs The left Result
rhs The right Result
Returns
The concatinated Result
Definition at line 98 of file Result.cpp.
References contextJson(), mSuccess, result_json, and success().
operator+=()
Result & operator+= (Result & lhs, const Result & rhs) related
Append one result to an existing one.
Both of the contexts are merged. The entires in lhs have the rhs context applied to them, and viceversa as well
Parameters
lhs The existing Result to add to
rhs The (usually temporary) result to be added into lhs.
Returns
*this
Definition at line 119 of file Result.cpp.
References contextJson(), mSuccess, result_json, and success().
operator<<()
std::ostream & operator<< (std::ostream & lhs, const Result & rhs) related
Stream operator.
Parameters
lhs The stream
rhs The Result to print to lhs
Returns
lhs after printing
Definition at line 184 of file Result.hpp.
References dump().
The documentation for this struct was generated from the following files:
libchigraph/include/chi/Result.hpp
libchigraph/src/Result.cpp