chigraph: chi::Subprocess Struct Reference
chi::Subprocess Struct Reference
Provides an platform-independent abstraction for creating subprocesses.
#include <chi/Subprocess.hpp>
Public Types
using pipeHandler = std::function< void(const char *data, size_t size)>
The function type for recieving data from pipes.
Public Member Functions
Subprocess (const boost::filesystem::path &pathToExecutable)
Construct a Subprocess with a path to an executable.
~Subprocess ()
Wait for the process to exit and close all open handles.
Result start ()
Start the process.
bool started () const
Check if the child has started (start() has been called)
Setup Functions
Setup functions are called after the cosntructor, but before start().
Most of them cannot be called after start(). They are used to set parameters for the program's execution
template<typename ForwardIterator >
void setArguments (const ForwardIterator &begin, const ForwardIterator &end)
Set the arguments for the program with a begin and end iterator.
template<typename Range >
void setArguments (Range &&range)
Set the arguments for the program with a range.
void setArguments (std::initializer_list< const char *> init)
Set the arguments for the program with an initializer_list.
const std::vector< std::string > & arguments () const
Get the currently set arguments for the program.
void attachToStdOut (pipeHandler stdOutHandler)
Attach a function handler to the child stdout.
void attachToStdErr (pipeHandler stdErrHandler)
Attach a function handler to the child stderr.
void attachStringToStdOut (std::string &str)
Attach a string to stdout.
void attachStringToStdErr (std::string &str)
Attach a string to stderr.
void setWorkingDirectory (boost::filesystem::path newWd)
Set the working directory of the process.
Runtime Functions
These functions are called while the process has started (ie after start() is called)
Result pushToStdIn (const char *data, size_t size)
Pushes data to the stdin stream of the child process.
Result closeStdIn ()
Close the STDIN stream (send an EOF)
bool isStdInClosed () const
Checks if the stdin is closed.
void kill ()
Kill the child process On POSIX, this sends SIGINT.
void wait ()
Wait for the process to complete.
int exitCode ()
Wait and gets the exit code.
bool running () const
Check if the process is still running.
Detailed Description
Provides an platform-independent abstraction for creating subprocesses.
On OSX and Linux, this uses the POSIX api (pipe(), fork(), exec(), write(), read(), etc) and on windows it uses the win32 API (CreatePipe(), CreateProcess(), ReadFile(), etc)
Usage is you create a Subprocess class:
    chi::Subprocess child{"/bin/sh"};
Now you can use any of the Setup Functions (see above):
    child.setArguments({"-c", "echo hi"});
    std::string stdOut;
    child.attachStringToStdOut(stdOut);
Once you're sure all youre setup variables are correctly set, start the process. You cannot change any of the setup values once you have called start()
    chi::Result res;
    res += child.start();
    if (!res) {
        std::cerr << res << std::endl;
        return 1;
    }
Now, you can use running() to see if the process has exited yet. We'll just use exitCode() to wait for the process to complete and get its exit code:
    int exitCode = child.exitCode();
    if (exitCode != 0) {
        std::cerr << "Failed run /bin/sh -c 'echo hi'" << std::endl;
        return 1;
    }
Code for this example can be found in examples/SubprocessExample.cpp
Examples:
SubprocessExample.cpp.
Definition at line 42 of file Subprocess.hpp.
Constructor & Destructor Documentation
Subprocess()
chi::Subprocess::Subprocess (const boost::filesystem::path & pathToExecutable)
Construct a Subprocess with a path to an executable.
Precondition
boost::filesystem::is_regular_file(pathToExecutable)
Definition at line 525 of file Subprocess.cpp.
Member Function Documentation
arguments()
const std::vector<std::string>& chi::Subprocess::arguments () const inline
Get the currently set arguments for the program.
Returns
The arguments
Definition at line 94 of file Subprocess.hpp.
attachStringToStdErr()
void chi::Subprocess::attachStringToStdErr (std::string & str) inline
Attach a string to stderr.
Everything added to the string is appended. This is just a convenicence function, it just calls attachToStdout with a function appending the data to the string.
Parameters
str The string to append stderr to
Note
Don't try to read from str while the program is running, it could create a race condition.
Precondition
!started()
Definition at line 134 of file Subprocess.hpp.
References attachToStdErr().
attachStringToStdOut()
void chi::Subprocess::attachStringToStdOut (std::string & str) inline
Attach a string to stdout.
Everything added to the string is appended. This is just a convenicence function, it just calls attachToStdout with a function appending the data to the string.
Parameters
str The string to append stdout to
Note
Don't try to read from str while the program is running, it could create a race condition.
Precondition
!started()
Definition at line 124 of file Subprocess.hpp.
References attachToStdOut().
attachToStdErr()
void chi::Subprocess::attachToStdErr (pipeHandler stdErrHandler) inline
Attach a function handler to the child stderr.
Every time data is recieved through the stderr pipe of the child, it will be sent to this handler
Parameters
stdErrHandler The handler
Note
stdErrHandler will exclusively be called from another thread.
Precondition
!started()
Definition at line 112 of file Subprocess.hpp.
References started().
Referenced by attachStringToStdErr().
attachToStdOut()
void chi::Subprocess::attachToStdOut (pipeHandler stdOutHandler) inline
Attach a function handler to the child stdout.
Every time data is recieved through the stdout pipe of the child, it will be sent to this handler
Parameters
stdOutHandler The handler
Note
stdOutHandler will exclusively be called from another thread.
Precondition
!started()
Definition at line 101 of file Subprocess.hpp.
References started().
Referenced by attachStringToStdOut().
closeStdIn()
Result chi::Subprocess::closeStdIn ()
Close the STDIN stream (send an EOF)
Returns
The Result
Precondition
!isStdInClosed()
running()
Postcondition
isStdInClosed()
Definition at line 351 of file Subprocess.cpp.
References chi::Result::addEntry(), isStdInClosed(), and running().
Referenced by started().
exitCode()
int chi::Subprocess::exitCode ()
Wait and gets the exit code.
Returns
The exit code. 0 for success.
Precondition
started()
Definition at line 495 of file Subprocess.cpp.
References started().
Referenced by isStdInClosed().
isStdInClosed()
bool chi::Subprocess::isStdInClosed () const inline
Checks if the stdin is closed.
Returns
true if it is, false otherwise
Definition at line 177 of file Subprocess.hpp.
References exitCode(), kill(), running(), and wait().
Referenced by closeStdIn(), pushToStdIn(), and ~Subprocess().
kill()
void chi::Subprocess::kill ()
Kill the child process On POSIX, this sends SIGINT.
Precondition
started()
Definition at line 482 of file Subprocess.cpp.
References started().
Referenced by isStdInClosed().
pushToStdIn()
Result chi::Subprocess::pushToStdIn (const char * data, size_t size)
Pushes data to the stdin stream of the child process.
Parameters
data The pointer to the start of the data
size How long the data is
Precondition
started()
!isStdInClosed()
Definition at line 337 of file Subprocess.cpp.
References chi::Result::addEntry(), isStdInClosed(), and started().
Referenced by started().
running()
bool chi::Subprocess::running () const
Check if the process is still running.
Returns
true if it's still running, false otherwise
Precondition
started()
Definition at line 509 of file Subprocess.cpp.
References started().
Referenced by closeStdIn(), and isStdInClosed().
setArguments() [1/3]
template<typename ForwardIterator > void chi::Subprocess::setArguments (const ForwardIterator & begin, const ForwardIterator & end) inline
Set the arguments for the program with a begin and end iterator.
Parameters
begin The start iterator of arguments. Should be an iterator of something converatable to std::string
end The end iterator. Should be an iterator of something converatable to std::string
Precondition
!started()
Examples:
SubprocessExample.cpp.
Definition at line 66 of file Subprocess.hpp.
References started().
Referenced by setArguments().
setArguments() [2/3]
template<typename Range > void chi::Subprocess::setArguments (Range && range) inline
Set the arguments for the program with a range.
Parameters
range The range. Must have begin() and end() functions, which return iterators.
Precondition
!started()
Definition at line 81 of file Subprocess.hpp.
References setArguments().
setArguments() [3/3]
void chi::Subprocess::setArguments (std::initializer_list< const char *> init) inline
Set the arguments for the program with an initializer_list.
Parameters
init the initializer list
Precondition
!started()
Definition at line 88 of file Subprocess.hpp.
References setArguments().
setWorkingDirectory()
void chi::Subprocess::setWorkingDirectory (boost::filesystem::path newWd) inline
Set the working directory of the process.
Parameters
newWd The new working directory
Precondition
!started()
Definition at line 141 of file Subprocess.hpp.
References start().
start()
Result chi::Subprocess::start ()
Start the process.
After this is called, most of the Setup Functions cannot be called anymore
Returns
The Result.
Precondition
!started()
Postcondition
started()
Definition at line 368 of file Subprocess.cpp.
References chi::Result::addEntry(), and started().
Referenced by setWorkingDirectory().
started()
bool chi::Subprocess::started () const inline
Check if the child has started (start() has been called)
Returns
True if it has, false otherwise
Definition at line 154 of file Subprocess.hpp.
References closeStdIn(), and pushToStdIn().
Referenced by attachToStdErr(), attachToStdOut(), exitCode(), kill(), pushToStdIn(), running(), setArguments(), start(), and wait().
wait()
void chi::Subprocess::wait ()
Wait for the process to complete.
Precondition
started()
Definition at line 487 of file Subprocess.cpp.
References started().
Referenced by isStdInClosed(), and ~Subprocess().
The documentation for this struct was generated from the following files:
libchigraph/include/chi/Subprocess.hpp
libchigraph/src/Subprocess.cpp