chigraph: chig::CModule Struct Reference
chig::CModule Struct Reference
The CModule is the module that supplies functionality to create C bindings.
#include <chig/CModule.hpp>
Public Member Functions
CModule (Context &ctx)
Contstructor–construct with a context. This is usually called by Context.
~CModule ()=default
Destructor.
Result addDependency (std::string newDepFullPath)
Context & context () const
llvm::DIType * debugTypeFromName (gsl::cstring_span<>) override
const std::unordered_set< std::string > & dependencies () const
std::string fullName () const
Result generateModule (llvm::Module &) override
std::string name () const
Result nodeTypeFromName (gsl::cstring_span<> typeName, const nlohmann::json &jsonData, std::unique_ptr< NodeType > *toFill) override
std::vector< std::string > nodeTypeNames () const override
bool removeDependency (gsl::cstring_span<> depName)
DataType typeFromName (gsl::cstring_span<> name) override
std::vector< std::string > typeNames () const override
Get the possible DataType names.
Detailed Description
The CModule is the module that supplies functionality to create C bindings.
Definition at line 18 of file CModule.hpp.
Member Function Documentation
addDependency()
Result chig::ChigModule::addDependency (std::string newDepFullPath) inherited
Add a dependency to the module Loads the module from context() if it isn't already loaded
Parameters
newDepFullPath The dependency, full path
Returns
The result
Definition at line 12 of file ChigModule.cpp.
References chig::ChigModule::context(), and chig::Context::loadModule().
Referenced by chig::ChigModule::dependencies(), and chig::JsonModule::JsonModule().
context()
Context& chig::ChigModule::context () const inline inherited
Get the Context that this module belongs to
Returns
The context
Definition at line 68 of file ChigModule.hpp.
References chig::ChigModule::generateModule().
Referenced by chig::ChigModule::addDependency(), chig::GraphFunction::GraphFunction(), chig::NodeType::NodeType(), chig::JsonModule::saveToDisk(), chig::JsonModule::sourceFilePath(), and chig::LangModule::typeFromName().
debugTypeFromName()
llvm::DIType* chig::CModule::debugTypeFromName (gsl::cstring_span<> name) inline override virtual
Get the debug info for a type from the name
Parameters
name The name of the type
Returns
The DIType, or nullptr if failed
Implements chig::ChigModule.
Definition at line 28 of file CModule.hpp.
dependencies()
const std::unordered_set<std::string>& chig::ChigModule::dependencies () const inline inherited
Get the dependencies
Returns
The dependencies
Definition at line 76 of file ChigModule.hpp.
References chig::ChigModule::addDependency().
Referenced by chig::JsonModule::toJSON().
fullName()
std::string chig::ChigModule::fullName () const inline inherited
Get the full name of the module
Returns
The name
Definition at line 65 of file ChigModule.hpp.
Referenced by chig::compileFunction(), chig::JsonModule::generateModule(), and chig::JsonModule::sourceFilePath().
generateModule()
Result chig::CModule::generateModule (llvm::Module & module) inline override virtual
Generate a llvm::Module from the module. Usually called by Context::compileModule
Parameters
module The llvm::Module to fill into – must be already filled with dependencies
Returns
The result
Implements chig::ChigModule.
Definition at line 31 of file CModule.hpp.
name()
std::string chig::ChigModule::name () const inline inherited
Get the short name of the module (the last bit)
Returns
The name
Definition at line 62 of file ChigModule.hpp.
Referenced by chig::JsonModule::graphFuncFromName(), nodeTypeFromName(), chig::JsonModule::nodeTypeFromName(), chig::DataType::qualifiedName(), chig::NodeType::qualifiedName(), and chig::JsonModule::toJSON().
nodeTypeFromName()
Result CModule::nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json & jsonData, std::unique_ptr< NodeType > * toFill) override virtual
Create a node type that is in the module from the name and json
Parameters
name The name of the node type to create
jsonData The extra JSON data for the node
toFill The NodeType object to fill
Returns
The result
Implements chig::ChigModule.
Definition at line 175 of file CModule.cpp.
References chig::Result::addEntry(), and chig::ChigModule::name().
nodeTypeNames()
std::vector<std::string> chig::CModule::nodeTypeNames () const inline override virtual
Get the possible node type names
Returns
A std::vector of the possible names
Implements chig::ChigModule.
Definition at line 29 of file CModule.hpp.
removeDependency()
bool chig::ChigModule::removeDependency (gsl::cstring_span<> depName) inline inherited
Remove a dependency Does not unload from context
Parameters
depName The name of the dependency to remove
Returns
If one was removed
Definition at line 87 of file ChigModule.hpp.
typeFromName()
DataType CModule::typeFromName (gsl::cstring_span<> name) override virtual
Get a DataType from the name
Parameters
name The name of the type
Returns
The data type, or an invalid DataType if failed
Implements chig::ChigModule.
Definition at line 169 of file CModule.cpp.
The documentation for this struct was generated from the following files:
include/chig/CModule.hpp
src/CModule.cpp