chigraph: chig::LangModule Struct Reference
chig::LangModule Struct Reference
The module that provides built-in operations like literals, math operations, etc.
#include <chig/LangModule.hpp>
Public Member Functions
LangModule (Context &ctx)
Default constructor, usually called from Context::loadModule("lang")
~LangModule ()=default
Destructor.
Result addDependency (std::string newDepFullPath)
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Context & context () const
Get the Context that this module belongs to.
llvm::DIType * debugTypeFromName (gsl::cstring_span<> name) override
Get the debug info for a type from the name.
const std::unordered_set< std::string > & dependencies () const
Get the dependencies.
std::string fullName () const
Get the full name of the module.
Result generateModule (llvm::Module &) override
Generate a llvm::Module from the module.
std::string name () const
Get the short name of the module (the last bit)
Result nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json &jsonData, std::unique_ptr< NodeType > *toFill) override
Create a node type that is in the module from the name and json.
std::vector< std::string > nodeTypeNames () const override
Get the possible node type names.
bool removeDependency (gsl::cstring_span<> depName)
Remove a dependency Does not unload from context.
DataType typeFromName (gsl::cstring_span<> name) override
Get a DataType from the name.
std::vector< std::string > typeNames () const override
Get the possible DataType names.
Detailed Description
The module that provides built-in operations like literals, math operations, etc.
Definition at line 17 of file LangModule.hpp.
Member Function Documentation
addDependency()
Result chig::ChigModule::addDependency (std::string newDepFullPath) inherited
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Parameters
newDepFullPath The dependency, full path
Returns
The result
Definition at line 15 of file ChigModule.cpp.
References chig::ChigModule::context(), and chig::Context::loadModule().
Referenced by chig::ChigModule::dependencies(), and chig::JsonModule::JsonModule().
context()
Context& chig::ChigModule::context () const inline inherited
Get the Context that this module belongs to.
Returns
The context
Definition at line 66 of file ChigModule.hpp.
References chig::ChigModule::generateModule().
Referenced by chig::ChigModule::addDependency(), chig::GraphFunction::GraphFunction(), LangModule(), chig::NodeType::NodeType(), chig::JsonModule::saveToDisk(), chig::JsonModule::sourceFilePath(), and typeFromName().
debugTypeFromName()
llvm::DIType * chig::LangModule::debugTypeFromName (gsl::cstring_span<> name) override virtual
Get the debug info for a type from the name.
Parameters
name The name of the type
Returns
The DIType, or nullptr if failed
Implements chig::ChigModule.
Definition at line 833 of file LangModule.cpp.
dependencies()
const std::unordered_set<std::string>& chig::ChigModule::dependencies () const inline inherited
Get the dependencies.
Returns
The dependencies
Definition at line 74 of file ChigModule.hpp.
References chig::ChigModule::addDependency().
Referenced by chig::JsonModule::toJSON().
fullName()
std::string chig::ChigModule::fullName () const inline inherited
Get the full name of the module.
Returns
The name
Definition at line 63 of file ChigModule.hpp.
Referenced by chig::Context::addModuleFromJson(), chig::compileFunction(), chig::JsonModule::generateModule(), and chig::JsonModule::sourceFilePath().
generateModule()
Result chig::LangModule::generateModule (llvm::Module & module) inline override virtual
Generate a llvm::Module from the module.
Usually called by Context::compileModule
Parameters
module The llvm::Module to fill into – must be already filled with dependencies
Returns
The result
Implements chig::ChigModule.
Definition at line 45 of file LangModule.hpp.
name()
std::string chig::ChigModule::name () const inline inherited
Get the short name of the module (the last bit)
Returns
The name
Definition at line 60 of file ChigModule.hpp.
Referenced by chig::JsonModule::graphFuncFromName(), chig::CModule::nodeTypeFromName(), chig::JsonModule::nodeTypeFromName(), chig::DataType::qualifiedName(), chig::NodeType::qualifiedName(), and chig::JsonModule::toJSON().
nodeTypeFromName()
Result chig::LangModule::nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json & jsonData, std::unique_ptr< NodeType > * toFill) override virtual
Create a node type that is in the module from the name and json.
Parameters
name The name of the node type to create
jsonData The extra JSON data for the node
toFill The NodeType object to fill
Returns
The result
Implements chig::ChigModule.
Definition at line 817 of file LangModule.cpp.
References chig::Result::addEntry().
nodeTypeNames()
std::vector<std::string> chig::LangModule::nodeTypeNames () const inline override virtual
Get the possible node type names.
Returns
A std::vector of the possible names
Implements chig::ChigModule.
Definition at line 31 of file LangModule.hpp.
removeDependency()
bool chig::ChigModule::removeDependency (gsl::cstring_span<> depName) inline inherited
Remove a dependency Does not unload from context.
Parameters
depName The name of the dependency to remove
Returns
If one was removed
Definition at line 85 of file ChigModule.hpp.
typeFromName()
DataType chig::LangModule::typeFromName (gsl::cstring_span<> name) override virtual
Get a DataType from the name.
Parameters
name The name of the type
Returns
The data type, or an invalid DataType if failed
Implements chig::ChigModule.
Definition at line 840 of file LangModule.cpp.
References chig::ChigModule::context().
Referenced by LangModule().
The documentation for this struct was generated from the following files:
include/chig/LangModule.hpp
src/LangModule.cpp