chigraph: chig::NodeInstance Struct Reference
chig::NodeInstance Struct Reference
An instance of a node.
#include <chig/NodeInstance.hpp>
Public Member Functions
NodeInstance (GraphFunction *func, std::unique_ptr< NodeType > nodeType, float posX, float posY, gsl::cstring_span<> nodeID)
Construct a nodeinstace with a type location and an ID, usually called from GraphFunction::insertNode.
NodeInstance (NodeInstance &&)=default
Move constructor.
NodeInstance (const NodeInstance &other, std::string id)
Copy constructor.
Context & context () const
Get the containing Context object.
GraphFunction & function () const
Get the containing GraphFunction.
std::string id () const
Get the ID of the instance, unique to the graph.
NodeInstance & operator= (NodeInstance &&)=default
Move assignment operator.
NodeInstance & operator= (const NodeInstance &)
Copy assignment operator.
void setType (std::unique_ptr< NodeType > newType)
Set the type of the node instance.
void setX (float newX)
Set the X location of the instance.
void setY (float newY)
Set the Y location of the instance.
NodeType & type ()
Get the type of the instance.
const NodeType & type () const
Get the type of the instance, const version.
float x () const
Get the X location of the instance.
float y () const
Get the Y location of the instance.
Public Attributes
std::vector< std::pair< NodeInstance *, size_t > > inputDataConnections
The connections that go into this node, data.
std::vector< std::vector< std::pair< NodeInstance *, size_t > > > inputExecConnections
The connections that lead to this node, exec.
std::vector< std::vector< std::pair< NodeInstance *, size_t > > > outputDataConnections
The connections that lead out of this node, data.
std::vector< std::pair< NodeInstance *, size_t > > outputExecConnections
The connections that go out of this node, exec.
Detailed Description
An instance of a node.
Definition at line 15 of file NodeInstance.hpp.
Constructor & Destructor Documentation
NodeInstance()
chig::NodeInstance::NodeInstance (GraphFunction * func, std::unique_ptr< NodeType > nodeType, float posX, float posY, gsl::cstring_span<> nodeID)
Construct a nodeinstace with a type location and an ID, usually called from GraphFunction::insertNode.
Parameters
func The function this nodeInstance belongs to
nodeType The type that the node is
posX The X location of the node
posY The Y location of the node
nodeID The unique ID for the node
Definition at line 9 of file NodeInstance.cpp.
References inputDataConnections, inputExecConnections, outputDataConnections, outputExecConnections, and type().
Member Function Documentation
id()
std::string chig::NodeInstance::id () const inline
Get the ID of the instance, unique to the graph.
Returns
The ID
Definition at line 62 of file NodeInstance.hpp.
Referenced by chig::disconnectData(), chig::disconnectExec(), operator=(), chig::GraphFunction::removeNode(), setType(), and chig::validateFunctionConnectionsAreTwoWay().
setType()
void chig::NodeInstance::setType (std::unique_ptr< NodeType > newType)
Set the type of the node instance.
Parameters
newType The new type
Definition at line 56 of file NodeInstance.cpp.
References chig::NodeType::dataInputs(), chig::NodeType::dataOutputs(), chig::disconnectData(), chig::disconnectExec(), id(), inputDataConnections, inputExecConnections, outputDataConnections, outputExecConnections, and type().
setX()
void chig::NodeInstance::setX (float newX) inline
Set the X location of the instance.
Parameters
newX The new X coordinate
Definition at line 56 of file NodeInstance.hpp.
setY()
void chig::NodeInstance::setY (float newY) inline
Set the Y location of the instance.
Parameters
newY The new Y coordinate
Definition at line 59 of file NodeInstance.hpp.
type() [1/2]
NodeType& chig::NodeInstance::type () inline
Get the type of the instance.
Returns
The type
Definition at line 44 of file NodeInstance.hpp.
Referenced by chig::connectData(), chig::connectExec(), chig::disconnectData(), chig::disconnectExec(), NodeInstance(), operator=(), and setType().
type() [2/2]
const NodeType& chig::NodeInstance::type () const inline
Get the type of the instance, const version.
Returns
The type
Definition at line 47 of file NodeInstance.hpp.
x()
float chig::NodeInstance::x () const inline
Get the X location of the instance.
Returns
The X coordinate
Definition at line 50 of file NodeInstance.hpp.
Referenced by NodeInstance(), and operator=().
y()
float chig::NodeInstance::y () const inline
Get the Y location of the instance.
Returns
The Y coordinate
Definition at line 53 of file NodeInstance.hpp.
Referenced by operator=().
The documentation for this struct was generated from the following files:
include/chig/NodeInstance.hpp
src/NodeInstance.cpp