chigraph: chig::Result Struct Reference
chig::Result Struct Reference
The result object, used for identifiying errors with good diagnostics.
#include <chig/Result.hpp>
Public Member Functions
Result ()
Default constructor; defaults to success.
void addEntry (const char *ec, const char *overview, nlohmann::json data)
Add a entry to the result, either a warning or an error.
std::string dump () const
Dump to a pretty-printed error message.
operator bool ()
Success test.
bool operator! ()
!Success test
Public Attributes
nlohmann::json result_json
The result JSON.
bool success
if it is successful
Related Functions
(Note that these are not member functions.)
Result operators
Result operator+ (const Result &lhs, const Result &rhs)
Append two Result objects.
Result & operator+= (Result &lhs, const Result &rhs)
Append one result to an existing one.
std::ostream & operator<< (std::ostream &lhs, const Result &rhs)
Stream operator.
Detailed Description
The result object, used for identifiying errors with good diagnostics.
Usage:
If you want to construct a default result object, just call the default constructor:
Result res;
res is the most common name for an error object, prefer it to other names.
When an error, warning, or just some event that requries logging needs to be added to the result object, call Result::addEntry:
Result res;
res.addEntry("E231", "Some error occured", {{"Line Number", 34}});
Note the E at the beginning of the error code, this is important. If it's an E, it's considered an error, and will mark the result as errored. If it's a W, then it's logged, but it's still considred successful.
If you're calling another operation that emits a Result object, then there's an easy to integrate that result object: the opeartor+=
Result res;
res += connectExec(...); // or any function that returns a Result
Implementation Details:
Result objects store a json object that represents the error metadata. It's an array, each being an object containing three objects:
errorcode: The errorcode. This is an identifier representng the error: a character followed by a number. The value of the character changes the behaviour:
E: it's an error and sets success to false.
W: it's a warning
I: it's just info
If it's anything else, that it will cause an assertion
overview: A simple string representing the generics of the problem. It shouldn't differ from error to error, if you need to include specifics use the data element
data: Extra metadata for the error, including context and how the error occured.
Definition at line 58 of file Result.hpp.
Member Function Documentation
addEntry()
void chig::Result::addEntry (const char * ec, const char * overview, nlohmann::json data) inline
Add a entry to the result, either a warning or an error.
Parameters
ec The error/warning code. If it starts with E, then it is an error and success is set to false, if it starts with a W it's a warning and success can stay true if it is still true.
overview Basic overview of the error, this shouldn't change based on the instance of the error
data The detailed description this instance of the error
Definition at line 68 of file Result.hpp.
References result_json, and success.
Referenced by chig::compileFunction(), chig::Context::compileModule(), chig::connectData(), chig::connectExec(), chig::createGraphFunctionDeclarationFromJson(), chig::disconnectData(), chig::disconnectExec(), chig::GraphFunction::insertNode(), chig::interpretLLVMIR(), chig::jsonToGraphFunction(), chig::jsonToGraphModule(), chig::jsonToGraphStruct(), chig::Context::loadModule(), chig::Context::nodeTypeFromModule(), chig::LangModule::nodeTypeFromName(), chig::CModule::nodeTypeFromName(), chig::GraphModule::nodeTypeFromName(), chig::GraphModule::saveToDisk(), chig::Context::typeFromModule(), and chig::validateFunctionConnectionsAreTwoWay().
Friends And Related Function Documentation
operator+()
Result operator+ (const Result & lhs, const Result & rhs) related
Append two Result objects.
Parameters
lhs The left error
rhs The right error
Returns
The concatinated errors
Definition at line 98 of file Result.hpp.
References result_json, and success.
operator+=()
Result & operator+= (Result & lhs, const Result & rhs) related
Append one result to an existing one.
Parameters
lhs The existing Result to add to
rhs The (usually temporary) result to be added into lhs
Returns
*this
Definition at line 114 of file Result.hpp.
References result_json, and success.
operator<<()
std::ostream & operator<< (std::ostream & lhs, const Result & rhs) related
Stream operator.
Parameters
lhs The stream
rhs The Result to print to lhs
Returns
lhs after printing
Definition at line 128 of file Result.hpp.
References dump().
The documentation for this struct was generated from the following files:
include/chig/Result.hpp
src/Result.cpp