chigraph: chig::GraphModule Struct Reference
chig::GraphModule Struct Reference
Module that holds graph functions.
#include <chig/GraphModule.hpp>
Public Member Functions
GraphModule (Context &cont, std::string fullName, gsl::span< std::string > dependencies)
Construct a GraphModule.
GraphModule (const GraphModule &)=delete
GraphModule (GraphModule &&)=delete
Result addDependency (std::string newDepFullPath)
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Context & context () const
Get the Context that this module belongs to.
boost::bimap< unsigned, NodeInstance * > createLineNumberAssoc () const
Create the associations from line number and function in debug info.
const std::unordered_set< std::string > & dependencies () const
Get the dependencies.
std::string fullName () const
Get the full name of the module.
Result generateModule (llvm::Module &module) override
Generate a llvm::Module from the module.
std::string name () const
Get the short name of the module (the last bit)
Result nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json &jsonData, std::unique_ptr< NodeType > *toFill) override
Create a node type that is in the module from the name and json.
std::vector< std::string > nodeTypeNames () const override
Get the possible node type names.
GraphModule & operator= (const GraphModule &)=delete
GraphModule & operator= (GraphModule &&)=delete
bool removeDependency (gsl::cstring_span<> depName)
Remove a dependency Does not unload from context.
Result saveToDisk () const
Serialize to disk in the context.
boost::filesystem::path sourceFilePath () const
Get the path to the source file It's not garunteed to exist, because it could have not been saved.
DataType typeFromName (gsl::cstring_span<>) override
Get a DataType from the name.
std::vector< std::string > typeNames () const override
Get the possible DataType names.
Function Creation and Manipulation
GraphFunction * getOrCreateFunction (gsl::cstring_span<> name, std::vector< std::pair< DataType, std::string >> dataIns, std::vector< std::pair< DataType, std::string >> dataOuts, std::vector< std::string > execIns, std::vector< std::string > execOuts, bool *inserted=nullptr)
Create a new function if it does't already exist.
bool removeFunction (gsl::cstring_span<> name)
Remove a function from the module.
void removeFunction (GraphFunction *func)
Remove a function from the module.
GraphFunction * graphFuncFromName (gsl::cstring_span<> name) const
Get a function from the name.
const std::vector< std::unique_ptr< GraphFunction > > & functions () const
Get functions.
Struct Creation and Manipulation
const std::vector< std::unique_ptr< GraphStruct > > & structs () const
GraphStruct * structFromName (gsl::cstring_span<> name) const
Get a struct by name.
GraphStruct * getOrCreateStruct (std::string name, bool *inserted=nullptr)
Create a new struct in the module.
bool removeStruct (gsl::cstring_span<> name)
Remove a struct from the module by name.
void removeStruct (GraphStruct *tyToDel)
Remove a struct from the module by pointer.
Detailed Description
Module that holds graph functions.
Definition at line 16 of file GraphModule.hpp.
Constructor & Destructor Documentation
GraphModule()
chig::GraphModule::GraphModule (Context & cont, std::string fullName, gsl::span< std::string > dependencies)
Construct a GraphModule.
Parameters
cont The context
fullName The full name of the module
dependencies The dependencies
Definition at line 95 of file GraphModule.cpp.
References chig::ChigModule::addDependency().
Member Function Documentation
addDependency()
Result chig::ChigModule::addDependency (std::string newDepFullPath) inherited
Add a dependency to the module Loads the module from context() if it isn't already loaded.
Parameters
newDepFullPath The dependency, full path
Returns
The result
Definition at line 14 of file ChigModule.cpp.
References chig::ChigModule::context(), and chig::Context::loadModule().
Referenced by chig::ChigModule::dependencies(), and GraphModule().
context()
Context& chig::ChigModule::context () const inline inherited
Get the Context that this module belongs to.
Returns
The context
Definition at line 60 of file ChigModule.hpp.
References chig::ChigModule::generateModule().
Referenced by chig::ChigModule::addDependency(), chig::createGraphFunctionDeclarationFromJson(), chig::jsonToGraphStruct(), chig::LangModule::LangModule(), chig::NodeType::NodeType(), saveToDisk(), sourceFilePath(), and chig::LangModule::typeFromName().
createLineNumberAssoc()
boost::bimap< unsigned int, NodeInstance * > chig::GraphModule::createLineNumberAssoc () const
Create the associations from line number and function in debug info.
Returns
A bimap of function to line number
Definition at line 229 of file GraphModule.cpp.
References functions().
Referenced by chig::compileFunction(), and typeNames().
dependencies()
const std::unordered_set<std::string>& chig::ChigModule::dependencies () const inline inherited
Get the dependencies.
Returns
The dependencies
Definition at line 68 of file ChigModule.hpp.
References chig::ChigModule::addDependency().
Referenced by chig::graphModuleToJson().
fullName()
std::string chig::ChigModule::fullName () const inline inherited
Get the full name of the module.
Returns
The name
Definition at line 57 of file ChigModule.hpp.
Referenced by chig::Context::addModuleFromJson(), chig::compileFunction(), generateModule(), and sourceFilePath().
functions()
const std::vector<std::unique_ptr<GraphFunction> >& chig::GraphModule::functions () const inline
Get functions.
Returns
The functions
Definition at line 91 of file GraphModule.hpp.
References getOrCreateStruct(), removeStruct(), and structFromName().
Referenced by createLineNumberAssoc(), and chig::graphModuleToJson().
generateModule()
Result chig::GraphModule::generateModule (llvm::Module & module) override virtual
Generate a llvm::Module from the module.
Usually called by Context::compileModule
Parameters
module The llvm::Module to fill into – must be already filled with dependencies
Returns
The result
Implements chig::ChigModule.
Definition at line 101 of file GraphModule.cpp.
References chig::compileFunction(), chig::ChigModule::fullName(), chig::mangleFunctionName(), and sourceFilePath().
Referenced by typeNames().
getOrCreateFunction()
GraphFunction * chig::GraphModule::getOrCreateFunction (gsl::cstring_span<> name, std::vector< std::pair< DataType, std::string >> dataIns, std::vector< std::pair< DataType, std::string >> dataOuts, std::vector< std::string > execIns, std::vector< std::string > execOuts, bool * inserted = nullptr)
Create a new function if it does't already exist.
Parameters
name The name of the new function
dataIns The data inputs to the function
dataOuts The data outputs to the function
execIns The exec inputs to the function
execOuts The exec outputs to the function
inserted Pointer of a bool to fill; sets to true if it was inserted and false if it already existed
Returns
The function
Definition at line 156 of file GraphModule.cpp.
References graphFuncFromName().
Referenced by chig::createGraphFunctionDeclarationFromJson(), and sourceFilePath().
getOrCreateStruct()
GraphStruct * chig::GraphModule::getOrCreateStruct (std::string name, bool * inserted = nullptr)
Create a new struct in the module.
Parameters
name The name of the struct True if the struct was new, optional
Returns
The new struct
Definition at line 262 of file GraphModule.cpp.
References structFromName().
Referenced by functions(), and chig::jsonToGraphStruct().
graphFuncFromName()
GraphFunction * chig::GraphModule::graphFuncFromName (gsl::cstring_span<> name) const
Get a function from the name.
Parameters
name The name to get
Returns
The GraphFunction or nullptr if it doesn't exist
Definition at line 197 of file GraphModule.cpp.
References chig::ChigModule::name().
Referenced by getOrCreateFunction(), nodeTypeFromName(), removeFunction(), and sourceFilePath().
name()
std::string chig::ChigModule::name () const inline inherited
Get the short name of the module (the last bit)
Returns
The name
Definition at line 54 of file ChigModule.hpp.
Referenced by graphFuncFromName(), chig::graphModuleToJson(), chig::GraphFunction::nodesWithType(), chig::CModule::nodeTypeFromName(), nodeTypeFromName(), chig::DataType::qualifiedName(), chig::NodeType::qualifiedName(), removeStruct(), and structFromName().
nodeTypeFromName()
Result chig::GraphModule::nodeTypeFromName (gsl::cstring_span<> name, const nlohmann::json & jsonData, std::unique_ptr< NodeType > * toFill) override virtual
Create a node type that is in the module from the name and json.
Parameters
name The name of the node type to create
jsonData The extra JSON data for the node
toFill The NodeType object to fill
Returns
The result
Implements chig::ChigModule.
Definition at line 205 of file GraphModule.cpp.
References chig::Result::addEntry(), graphFuncFromName(), and chig::ChigModule::name().
nodeTypeNames()
std::vector< std::string > chig::GraphModule::nodeTypeNames () const override virtual
Get the possible node type names.
Returns
A std::vector of the possible names
Implements chig::ChigModule.
Definition at line 221 of file GraphModule.cpp.
Referenced by typeFromName().
removeDependency()
bool chig::ChigModule::removeDependency (gsl::cstring_span<> depName) inline inherited
Remove a dependency Does not unload from context.
Parameters
depName The name of the dependency to remove
Returns
If one was removed
Definition at line 79 of file ChigModule.hpp.
removeFunction() [1/2]
bool chig::GraphModule::removeFunction (gsl::cstring_span<> name)
Remove a function from the module.
Parameters
name The name of the function to remove
Returns
True if there was a function matching name that was removed
Definition at line 177 of file GraphModule.cpp.
References graphFuncFromName().
Referenced by sourceFilePath().
removeFunction() [2/2]
void chig::GraphModule::removeFunction (GraphFunction * func)
Remove a function from the module.
Parameters
func The function to remove
Definition at line 187 of file GraphModule.cpp.
removeStruct() [1/2]
bool chig::GraphModule::removeStruct (gsl::cstring_span<> name)
Remove a struct from the module by name.
Parameters
name The name of the struct to remove
Returns
True if a struct was actually removed, false if no struct by that name existed
Definition at line 276 of file GraphModule.cpp.
References chig::ChigModule::name().
Referenced by functions().
removeStruct() [2/2]
void chig::GraphModule::removeStruct (GraphStruct * tyToDel)
Remove a struct from the module by pointer.
Parameters
tyToDel Struct to delete, must be in this module
Definition at line 286 of file GraphModule.cpp.
References chig::GraphStruct::module().
saveToDisk()
Result chig::GraphModule::saveToDisk () const
Serialize to disk in the context.
Returns
The Result
Definition at line 125 of file GraphModule.cpp.
References chig::Result::addEntry(), chig::ChigModule::context(), chig::graphModuleToJson(), and sourceFilePath().
Referenced by typeNames().
sourceFilePath()
boost::filesystem::path chig::GraphModule::sourceFilePath () const inline
Get the path to the source file It's not garunteed to exist, because it could have not been saved.
Returns
The path
Definition at line 54 of file GraphModule.hpp.
References chig::ChigModule::context(), chig::ChigModule::fullName(), getOrCreateFunction(), graphFuncFromName(), removeFunction(), and chig::Context::workspacePath().
Referenced by generateModule(), and saveToDisk().
structFromName()
GraphStruct * chig::GraphModule::structFromName (gsl::cstring_span<> name) const
Get a struct by name.
Parameters
name The name of the struct
Returns
The struct or nullptr if not found
Definition at line 252 of file GraphModule.cpp.
References chig::ChigModule::name().
Referenced by functions(), and getOrCreateStruct().
typeFromName()
DataType chig::GraphModule::typeFromName (gsl::cstring_span<> name) inline override virtual
Get a DataType from the name.
Parameters
name The name of the type
Returns
The data type, or an invalid DataType if failed
Implements chig::ChigModule.
Definition at line 35 of file GraphModule.hpp.
References nodeTypeNames().
The documentation for this struct was generated from the following files:
include/chig/GraphModule.hpp
src/GraphModule.cpp